server {
    listen 8081;
    server_name _;
    access_log off;

    location = /healthz {
        default_type text/plain;
        return 200 "ok\n";
    }

    location /google-fonts/ {
        limit_except GET { deny all; }

        proxy_pass https://raw.githubusercontent.com/google/fonts/ec0464b978de222073645d6d3366f3fdf03376d8/;
        proxy_ssl_server_name on;
        proxy_ssl_name raw.githubusercontent.com;
        proxy_set_header Host raw.githubusercontent.com;
        proxy_pass_request_headers off;
        proxy_redirect off;
        proxy_intercept_errors on;
        proxy_connect_timeout 5s;
        proxy_read_timeout 15s;
        proxy_send_timeout 5s;
    }

    location / {
        return 404;
    }
}
