"""Família construtivista: tensão diagonal, sinal radial e contracampo."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "constructivist-dynamics"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _wedge(ir: BrandIR) -> LayoutSpec:
    layout_id = "constructivist-wedge-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Construtivismo — Corte ascendente",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="vertical-rail",
                shape="rectangle",
                area=(0, 0, 62, 1350),
                color_token="color.primary",
                z_index=1,
            ),
            ShapeLayer(
                id="rise-step-one",
                shape="rectangle",
                area=(62, 748, 254, 330),
                color_token="color.primary",
                opacity=0.18,
                z_index=1,
            ),
            ShapeLayer(
                id="rise-step-two",
                shape="rectangle",
                area=(316, 598, 254, 480),
                color_token="color.primary",
                opacity=0.46,
                z_index=1,
            ),
            ShapeLayer(
                id="rise-step-three",
                shape="rectangle",
                area=(570, 448, 448, 630),
                color_token="color.primary",
                z_index=1,
            ),
            ShapeLayer(
                id="counter-disc",
                shape="circle",
                area=(782, 100, 236, 236),
                color_token="color.text",
                z_index=2,
            ),
            ShapeLayer(
                id="closing-rule",
                shape="rectangle",
                area=(100, 1200, 918, 8),
                color_token="color.text",
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=48,
                area=(100, 82, 476, 38),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_weight=750,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                color_token="color.background",
                max_chars=42,
                area=(806, 190, 188, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=750,
                text_align="center",
                letter_spacing_em=0.05,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=34,
                area=(100, 188, 622, 300),
                fit="fixed",
                font_size_px=108,
                font_weight=900,
                line_height=0.86,
                letter_spacing_em=-0.06,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=3,
                area=(616, 666, 350, 188),
                fit="fixed",
                font_size_px=170,
                font_weight=900,
                line_height=0.82,
                text_align="right",
                letter_spacing_em=-0.07,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                color_token="color.background",
                max_chars=112,
                area=(616, 876, 350, 142),
                fit="fixed",
                required=False,
                font_size_px=24,
                font_weight=600,
                line_height=1.18,
                text_align="right",
                z_index=10,
            ),
            logo_slot(ir, (852, 1146, 142, 142)),
        ],
        scene_graph=SceneGraph(
            roots=["wedge-root"],
            groups=[
                SceneGroup(
                    id="wedge-root",
                    kind="frame",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "vertical-rail",
                        "ascending-field",
                        "counter-disc",
                        "closing-rule",
                        "upper-message",
                        "counter-message",
                        "signature",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="ascending-field",
                    kind="stack",
                    direction="horizontal",
                    gap_px=0,
                    area=(62, 448, 956, 630),
                    children=["rise-step-one", "rise-step-two", "rise-step-three"],
                ),
                SceneGroup(
                    id="upper-message",
                    kind="stack",
                    direction="vertical",
                    gap_px=68,
                    area=(100, 82, 622, 406),
                    children=["kicker", "headline"],
                ),
                SceneGroup(
                    id="counter-message",
                    kind="stack",
                    direction="vertical",
                    gap_px=22,
                    area=(616, 666, 350, 352),
                    children=["index", "body"],
                ),
            ],
        ),
    )


def _broadcast(ir: BrandIR) -> LayoutSpec:
    layout_id = "constructivist-broadcast-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Construtivismo — Sinal de transmissão",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="signal-disc",
                shape="circle",
                area=(74, 164, 548, 548),
                color_token="color.primary",
                z_index=1,
            ),
            ShapeLayer(
                id="signal-counter",
                shape="circle",
                area=(230, 320, 236, 236),
                color_token="color.background",
                z_index=2,
            ),
            ShapeLayer(
                id="broadcast-bar-one",
                shape="rectangle",
                area=(544, 258, 436, 30),
                color_token="color.text",
                opacity=0.28,
                z_index=3,
            ),
            ShapeLayer(
                id="broadcast-bar-two",
                shape="rectangle",
                area=(466, 334, 514, 46),
                color_token="color.text",
                opacity=0.58,
                z_index=3,
            ),
            ShapeLayer(
                id="broadcast-bar-three",
                shape="rectangle",
                area=(388, 426, 592, 66),
                color_token="color.text",
                z_index=3,
            ),
            ShapeLayer(
                id="lower-frequency-one",
                shape="rectangle",
                area=(74, 984, 246, 8),
                color_token="color.primary",
                opacity=0.24,
                z_index=1,
            ),
            ShapeLayer(
                id="lower-frequency-two",
                shape="rectangle",
                area=(74, 1022, 522, 8),
                color_token="color.primary",
                opacity=0.52,
                z_index=1,
            ),
            ShapeLayer(
                id="lower-frequency-three",
                shape="rectangle",
                area=(74, 1060, 906, 8),
                color_token="color.primary",
                z_index=1,
            ),
        ],
        slots=[
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(752, 72, 228, 126),
                fit="fixed",
                font_size_px=108,
                font_weight=900,
                line_height=0.84,
                text_align="right",
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="signal-word",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=12,
                area=(124, 526, 600, 164),
                fit="fixed",
                required=False,
                font_size_px=124,
                font_weight=900,
                line_height=0.84,
                letter_spacing_em=-0.06,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=46,
                area=(74, 752, 390, 38),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_weight=750,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=30,
                area=(458, 650, 522, 340),
                fit="fixed",
                font_size_px=96,
                font_weight=900,
                line_height=0.88,
                letter_spacing_em=-0.055,
                text_align="right",
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=124,
                area=(74, 1128, 534, 122),
                fit="fixed",
                required=False,
                font_size_px=23,
                font_weight=550,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(690, 1218, 290, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=700,
                text_align="right",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (74, 72, 126, 126)),
        ],
        scene_graph=SceneGraph(
            roots=["broadcast-root"],
            groups=[
                SceneGroup(
                    id="broadcast-root",
                    kind="group",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "signal-orbit",
                        "broadcast-bars",
                        "lower-frequency",
                        "signal-word",
                        "headline-frame",
                        "footer-row",
                        "index",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="signal-orbit",
                    kind="frame",
                    area=(74, 164, 548, 548),
                    children=["signal-disc", "signal-counter"],
                ),
                SceneGroup(
                    id="broadcast-bars",
                    kind="stack",
                    direction="vertical",
                    gap_px=46,
                    area=(388, 258, 592, 234),
                    children=["broadcast-bar-one", "broadcast-bar-two", "broadcast-bar-three"],
                ),
                SceneGroup(
                    id="lower-frequency",
                    kind="stack",
                    direction="vertical",
                    gap_px=30,
                    area=(74, 984, 906, 84),
                    children=[
                        "lower-frequency-one",
                        "lower-frequency-two",
                        "lower-frequency-three",
                    ],
                ),
                SceneGroup(
                    id="headline-frame",
                    kind="frame",
                    area=(74, 650, 906, 340),
                    children=["kicker", "headline"],
                ),
                SceneGroup(
                    id="footer-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=82,
                    area=(74, 1128, 906, 124),
                    children=["body", "signature"],
                ),
            ],
        ),
    )


def _counterfield(ir: BrandIR) -> LayoutSpec:
    layout_id = "constructivist-counterfield-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Construtivismo — Contracampo",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="left-field",
                shape="rectangle",
                area=(0, 0, 392, 1350),
                color_token="color.text",
                z_index=1,
            ),
            ShapeLayer(
                id="crossbar-wide",
                shape="rectangle",
                area=(216, 332, 806, 64),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="crossbar-narrow",
                shape="rectangle",
                area=(216, 428, 526, 18),
                color_token="color.primary",
                opacity=0.46,
                z_index=3,
            ),
            ShapeLayer(
                id="lower-block",
                shape="rectangle",
                area=(524, 872, 498, 318),
                color_token="color.primary",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="marker-disc",
                shape="circle",
                area=(310, 1108, 164, 164),
                color_token="color.primary",
                z_index=4,
            ),
        ],
        slots=[
            Slot(
                id="signature",
                kind="text",
                role="caption",
                color_token="color.background",
                max_chars=42,
                area=(68, 82, 256, 36),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=700,
                text_transform="uppercase",
                letter_spacing_em=0.1,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=3,
                area=(48, 170, 292, 304),
                fit="fixed",
                font_size_px=246,
                font_weight=900,
                line_height=0.8,
                letter_spacing_em=-0.08,
                fill_mode="stroke",
                stroke_color_token="color.background",
                stroke_width_px=3,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=48,
                area=(466, 88, 556, 36),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_weight=750,
                text_align="right",
                text_transform="uppercase",
                letter_spacing_em=0.19,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=36,
                area=(466, 508, 556, 322),
                fit="fixed",
                font_size_px=106,
                font_weight=900,
                line_height=0.88,
                letter_spacing_em=-0.055,
                text_align="right",
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=126,
                area=(552, 914, 420, 148),
                fit="fixed",
                required=False,
                font_size_px=24,
                line_height=1.2,
                text_align="right",
                z_index=10,
            ),
            logo_slot(ir, (76, 1150, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["counterfield-root"],
            groups=[
                SceneGroup(
                    id="counterfield-root",
                    kind="grid",
                    columns=2,
                    gap_px=74,
                    area=(0, 0, 1080, 1350),
                    children=["left-panel", "right-panel", "cross-bars", "marker-disc"],
                ),
                SceneGroup(
                    id="left-panel",
                    kind="stack",
                    direction="vertical",
                    gap_px=52,
                    area=(0, 0, 392, 1350),
                    children=["left-field", "signature", "index", "logo"],
                ),
                SceneGroup(
                    id="right-panel",
                    kind="stack",
                    direction="vertical",
                    gap_px=58,
                    area=(466, 88, 556, 1102),
                    children=["kicker", "headline", "lower-block", "body"],
                ),
                SceneGroup(
                    id="cross-bars",
                    kind="stack",
                    direction="vertical",
                    gap_px=32,
                    area=(216, 332, 806, 114),
                    children=["crossbar-wide", "crossbar-narrow"],
                ),
            ],
        ),
    )


def constructivist_dynamics_package(ir: BrandIR) -> TemplatePackage:
    """Publica três composições construtivistas com tensões espaciais próprias."""
    style = derive_style_system(ir)
    layouts = (_wedge(ir), _broadcast(ir), _counterfield(ir))
    samples = {
        "constructivist-wedge-post-4x5": {
            "kicker": "Direção como linguagem",
            "signature": "@sua-marca",
            "headline": "A direção muda tudo.",
            "index": "1",
            "body": "Forma, contraste e movimento organizam a mensagem em uma única tensão.",
        },
        "constructivist-broadcast-post-4x5": {
            "index": "2",
            "signal-word": "Agora",
            "kicker": "Sinal aberto",
            "headline": "Faça a ideia circular.",
            "body": "Um centro forte irradia a mensagem e conduz o olhar pelo quadro.",
            "signature": "@sua-marca",
        },
        "constructivist-counterfield-post-4x5": {
            "signature": "@sua-marca",
            "index": "3",
            "kicker": "Oposição produtiva",
            "headline": "Contraste também constrói.",
            "body": "Dois campos em conflito criam uma hierarquia clara e memorável.",
        },
    }
    intents = {
        "constructivist-wedge-post-4x5": (
            "Corte ascendente",
            "Construir impulso por massas escalonadas que sobem e comprimem a mensagem.",
        ),
        "constructivist-broadcast-post-4x5": (
            "Sinal de transmissão",
            "Irradiar a leitura a partir de uma órbita atravessada por barras de frequência.",
        ),
        "constructivist-counterfield-post-4x5": (
            "Contracampo",
            "Criar tensão entre um trilho escuro, um campo aberto e travessias cromáticas.",
        ),
    }
    compositions = []
    for layout in layouts:
        name, intent = intents[layout.id]
        compositions.append(
            TemplateComposition(
                id=layout.id,
                name_pt=name,
                intent_pt=intent,
                layout=layout,
                sample_content_pt=samples[layout.id],
                critical_nodes=["headline", "logo"],
                export_support=ExportSupport(pptx="native"),
            )
        )
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Construtivismo",
        title_pt="Construtivismo",
        description_pt=(
            "Três composições editáveis construídas por tensão, travessia e massas em movimento."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
