"""Família editorial para métricas, comparações e evidências verificáveis."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "data-evidence"
PACKAGE_VERSION = "1.0.0"


def _metric_layout(ir: BrandIR) -> LayoutSpec:
    layout_id = "evidence-hero-metric-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Dados e evidências — Métrica em primeiro plano",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=template_ref(PACKAGE_ID, PACKAGE_VERSION, layout_id),
        locked_layers=[
            ShapeLayer(
                id="metric-top-rule",
                shape="rectangle",
                area=(72, 142, 936, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
            ShapeLayer(
                id="metric-field",
                shape="rectangle",
                area=(72, 214, 604, 598),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="metric-axis",
                shape="rectangle",
                area=(676, 214, 2, 598),
                color_token="color.text",
                opacity=0.32,
                z_index=2,
            ),
            ShapeLayer(
                id="metric-delta-field",
                shape="rectangle",
                area=(92, 684, 242, 54),
                color_token="color.primary",
                opacity=0.16,
                z_index=2,
            ),
            ShapeLayer(
                id="metric-bar-one",
                shape="rectangle",
                area=(720, 414, 250, 18),
                color_token="color.primary",
                opacity=0.92,
                z_index=3,
            ),
            ShapeLayer(
                id="metric-bar-two",
                shape="rectangle",
                area=(720, 536, 184, 18),
                color_token="color.primary",
                opacity=0.62,
                z_index=3,
            ),
            ShapeLayer(
                id="metric-bar-three",
                shape="rectangle",
                area=(720, 658, 112, 18),
                color_token="color.primary",
                opacity=0.34,
                z_index=3,
            ),
            ShapeLayer(
                id="metric-bottom-rule",
                shape="rectangle",
                area=(72, 1168, 936, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(72, 78, 500, 32),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="period",
                kind="text",
                role="caption",
                max_chars=28,
                area=(720, 78, 288, 32),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=52,
                area=(92, 244, 544, 154),
                fit="fixed",
                font_size_px=54,
                font_weight=680,
                line_height=0.96,
                letter_spacing_em=-0.035,
                z_index=10,
            ),
            Slot(
                id="metric",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=12,
                area=(92, 430, 544, 196),
                fit="fixed",
                font_size_px=164,
                font_weight=700,
                line_height=0.82,
                letter_spacing_em=-0.07,
                z_index=10,
            ),
            Slot(
                id="delta",
                kind="text",
                role="caption",
                color_token="color.primary",
                max_chars=24,
                area=(110, 699, 206, 26),
                fit="fixed",
                font_size_px=15,
                font_weight=700,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.1,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=122,
                area=(72, 864, 604, 144),
                fit="fixed",
                required=False,
                font_size_px=21,
                line_height=1.3,
                z_index=10,
            ),
            Slot(
                id="label-one",
                kind="text",
                role="caption",
                max_chars=30,
                area=(720, 350, 288, 32),
                fit="fixed",
                font_size_px=14,
                font_weight=620,
                text_transform="uppercase",
                letter_spacing_em=0.1,
                z_index=10,
            ),
            Slot(
                id="label-two",
                kind="text",
                role="caption",
                max_chars=30,
                area=(720, 472, 288, 32),
                fit="fixed",
                font_size_px=14,
                font_weight=620,
                text_transform="uppercase",
                letter_spacing_em=0.1,
                z_index=10,
            ),
            Slot(
                id="label-three",
                kind="text",
                role="caption",
                max_chars=30,
                area=(720, 594, 288, 32),
                fit="fixed",
                font_size_px=14,
                font_weight=620,
                text_transform="uppercase",
                letter_spacing_em=0.1,
                z_index=10,
            ),
            Slot(
                id="source",
                kind="text",
                role="caption",
                max_chars=72,
                area=(720, 734, 288, 80),
                fit="fixed",
                required=False,
                font_size_px=13,
                line_height=1.35,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(72, 1214, 470, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (828, 1168, 100, 100)),
        ],
        scene_graph=SceneGraph(
            roots=["metric-root"],
            groups=[
                SceneGroup(
                    id="metric-root",
                    kind="frame",
                    area=(0, 0, 1080, 1350),
                    children=["metric-header", "metric-focus", "metric-proof", "metric-footer"],
                ),
                SceneGroup(
                    id="metric-header",
                    kind="frame",
                    area=(72, 78, 936, 66),
                    children=["kicker", "period", "metric-top-rule"],
                ),
                SceneGroup(
                    id="metric-focus",
                    kind="frame",
                    area=(72, 214, 606, 794),
                    children=[
                        "metric-field",
                        "metric-axis",
                        "headline",
                        "metric",
                        "metric-delta-field",
                        "delta",
                        "body",
                    ],
                ),
                SceneGroup(
                    id="metric-proof",
                    kind="frame",
                    area=(720, 350, 288, 464),
                    children=[
                        "label-one",
                        "metric-bar-one",
                        "label-two",
                        "metric-bar-two",
                        "label-three",
                        "metric-bar-three",
                        "source",
                    ],
                ),
                SceneGroup(
                    id="metric-footer",
                    kind="frame",
                    area=(72, 1168, 936, 120),
                    children=["metric-bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def _comparison_layout(ir: BrandIR) -> LayoutSpec:
    layout_id = "evidence-comparison-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Dados e evidências — Comparação lado a lado",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=template_ref(PACKAGE_ID, PACKAGE_VERSION, layout_id),
        locked_layers=[
            ShapeLayer(
                id="comparison-left-field",
                shape="rectangle",
                area=(56, 370, 450, 620),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="comparison-right-field",
                shape="rectangle",
                area=(574, 370, 450, 620),
                color_token="color.primary",
                opacity=0.18,
                z_index=1,
            ),
            ShapeLayer(
                id="comparison-spine",
                shape="rectangle",
                area=(538, 228, 4, 856),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="comparison-left-rule",
                shape="rectangle",
                area=(92, 472, 378, 3),
                color_token="color.text",
                opacity=0.34,
                z_index=2,
            ),
            ShapeLayer(
                id="comparison-right-rule",
                shape="rectangle",
                area=(610, 472, 378, 3),
                color_token="color.text",
                opacity=0.34,
                z_index=2,
            ),
            ShapeLayer(
                id="comparison-verdict-field",
                shape="rectangle",
                area=(210, 1038, 660, 102),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(56, 74, 460, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=58,
                area=(56, 134, 968, 178),
                fit="fixed",
                font_size_px=64,
                font_weight=690,
                line_height=0.94,
                letter_spacing_em=-0.04,
                z_index=10,
            ),
            Slot(
                id="label-left",
                kind="text",
                role="caption",
                max_chars=26,
                area=(92, 406, 378, 34),
                fit="fixed",
                font_size_px=14,
                font_weight=700,
                text_transform="uppercase",
                letter_spacing_em=0.14,
                z_index=10,
            ),
            Slot(
                id="label-right",
                kind="text",
                role="caption",
                max_chars=26,
                area=(610, 406, 378, 34),
                fit="fixed",
                font_size_px=14,
                font_weight=700,
                text_transform="uppercase",
                letter_spacing_em=0.14,
                z_index=10,
            ),
            Slot(
                id="value-left",
                kind="text",
                role="heading",
                max_chars=12,
                area=(92, 520, 378, 146),
                fit="fixed",
                font_size_px=108,
                font_weight=680,
                line_height=0.86,
                letter_spacing_em=-0.06,
                z_index=10,
            ),
            Slot(
                id="value-right",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=12,
                area=(610, 520, 378, 146),
                fit="fixed",
                font_size_px=108,
                font_weight=700,
                line_height=0.86,
                letter_spacing_em=-0.06,
                z_index=10,
            ),
            Slot(
                id="body-left",
                kind="text",
                role="body",
                max_chars=110,
                area=(92, 724, 378, 162),
                fit="fixed",
                required=False,
                font_size_px=19,
                line_height=1.34,
                z_index=10,
            ),
            Slot(
                id="body-right",
                kind="text",
                role="body",
                max_chars=110,
                area=(610, 724, 378, 162),
                fit="fixed",
                required=False,
                font_size_px=19,
                line_height=1.34,
                z_index=10,
            ),
            Slot(
                id="verdict",
                kind="text",
                role="body",
                max_chars=84,
                area=(242, 1064, 596, 52),
                fit="fixed",
                font_size_px=20,
                font_weight=650,
                line_height=1.2,
                text_align="center",
                z_index=10,
            ),
            Slot(
                id="source",
                kind="text",
                role="caption",
                max_chars=72,
                area=(56, 1194, 620, 58),
                fit="fixed",
                required=False,
                font_size_px=13,
                line_height=1.3,
                z_index=10,
            ),
            logo_slot(ir, (844, 1168, 100, 100)),
        ],
        scene_graph=SceneGraph(
            roots=["comparison-root"],
            groups=[
                SceneGroup(
                    id="comparison-root",
                    kind="grid",
                    columns=2,
                    gap_px=68,
                    area=(56, 74, 968, 1204),
                    children=["comparison-header", "comparison-panels", "comparison-summary"],
                ),
                SceneGroup(
                    id="comparison-header",
                    kind="frame",
                    area=(56, 74, 968, 238),
                    children=["kicker", "headline"],
                ),
                SceneGroup(
                    id="comparison-panels",
                    kind="grid",
                    columns=2,
                    gap_px=68,
                    area=(56, 370, 968, 620),
                    children=[
                        "comparison-left-field",
                        "comparison-right-field",
                        "comparison-spine",
                        "comparison-left-rule",
                        "comparison-right-rule",
                        "label-left",
                        "label-right",
                        "value-left",
                        "value-right",
                        "body-left",
                        "body-right",
                    ],
                ),
                SceneGroup(
                    id="comparison-summary",
                    kind="frame",
                    area=(56, 1038, 968, 240),
                    children=["comparison-verdict-field", "verdict", "source", "logo"],
                ),
            ],
        ),
    )


def _dashboard_layout(ir: BrandIR) -> LayoutSpec:
    layout_id = "evidence-dashboard-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Dados e evidências — Painel modular",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=template_ref(PACKAGE_ID, PACKAGE_VERSION, layout_id),
        locked_layers=[
            ShapeLayer(
                id="dashboard-card-one",
                shape="rectangle",
                area=(64, 470, 284, 260),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="dashboard-card-two",
                shape="rectangle",
                area=(398, 470, 284, 260),
                color_token="color.primary",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="dashboard-card-three",
                shape="rectangle",
                area=(732, 470, 284, 260),
                color_token="color.primary",
                opacity=0.22,
                z_index=1,
            ),
            ShapeLayer(
                id="dashboard-rail",
                shape="rectangle",
                area=(64, 828, 952, 4),
                color_token="color.text",
                opacity=0.28,
                z_index=2,
            ),
            ShapeLayer(
                id="dashboard-progress-one",
                shape="rectangle",
                area=(64, 892, 260, 14),
                color_token="color.primary",
                opacity=0.42,
                z_index=3,
            ),
            ShapeLayer(
                id="dashboard-progress-two",
                shape="rectangle",
                area=(64, 974, 522, 14),
                color_token="color.primary",
                opacity=0.7,
                z_index=3,
            ),
            ShapeLayer(
                id="dashboard-progress-three",
                shape="rectangle",
                area=(64, 1056, 828, 14),
                color_token="color.primary",
                opacity=1,
                z_index=3,
            ),
            ShapeLayer(
                id="dashboard-endpoint",
                shape="circle",
                area=(994, 1049, 22, 22),
                color_token="color.primary",
                z_index=4,
            ),
            ShapeLayer(
                id="dashboard-bottom-rule",
                shape="rectangle",
                area=(64, 1166, 952, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(64, 70, 460, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="period",
                kind="text",
                role="caption",
                max_chars=28,
                area=(700, 70, 316, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=54,
                area=(64, 144, 608, 190),
                fit="fixed",
                font_size_px=60,
                font_weight=690,
                line_height=0.94,
                letter_spacing_em=-0.045,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=96,
                area=(700, 162, 316, 144),
                fit="fixed",
                required=False,
                font_size_px=18,
                line_height=1.35,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="metric-one",
                kind="text",
                role="heading",
                max_chars=10,
                area=(88, 506, 236, 92),
                fit="fixed",
                font_size_px=72,
                font_weight=690,
                line_height=0.9,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="metric-two",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=10,
                area=(422, 506, 236, 92),
                fit="fixed",
                font_size_px=72,
                font_weight=690,
                line_height=0.9,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="metric-three",
                kind="text",
                role="heading",
                max_chars=10,
                area=(756, 506, 236, 92),
                fit="fixed",
                font_size_px=72,
                font_weight=690,
                line_height=0.9,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="label-one",
                kind="text",
                role="caption",
                max_chars=32,
                area=(88, 640, 236, 52),
                fit="fixed",
                font_size_px=14,
                line_height=1.25,
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="label-two",
                kind="text",
                role="caption",
                max_chars=32,
                area=(422, 640, 236, 52),
                fit="fixed",
                font_size_px=14,
                line_height=1.25,
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="label-three",
                kind="text",
                role="caption",
                max_chars=32,
                area=(756, 640, 236, 52),
                fit="fixed",
                font_size_px=14,
                line_height=1.25,
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="stage-one",
                kind="text",
                role="caption",
                max_chars=34,
                area=(344, 878, 250, 38),
                fit="fixed",
                font_size_px=14,
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="stage-two",
                kind="text",
                role="caption",
                max_chars=34,
                area=(606, 960, 250, 38),
                fit="fixed",
                font_size_px=14,
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="stage-three",
                kind="text",
                role="caption",
                max_chars=34,
                area=(734, 1042, 250, 38),
                fit="fixed",
                font_size_px=14,
                text_align="right",
                text_transform="uppercase",
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="source",
                kind="text",
                role="caption",
                max_chars=72,
                area=(64, 1202, 640, 54),
                fit="fixed",
                required=False,
                font_size_px=13,
                line_height=1.3,
                z_index=10,
            ),
            logo_slot(ir, (836, 1168, 100, 100)),
        ],
        scene_graph=SceneGraph(
            roots=["dashboard-root"],
            groups=[
                SceneGroup(
                    id="dashboard-root",
                    kind="stack",
                    direction="vertical",
                    gap_px=64,
                    area=(64, 70, 952, 1212),
                    children=[
                        "dashboard-header",
                        "dashboard-cards",
                        "dashboard-progress",
                        "dashboard-footer",
                    ],
                ),
                SceneGroup(
                    id="dashboard-header",
                    kind="group",
                    area=(64, 70, 952, 264),
                    children=["kicker", "period", "headline", "body"],
                ),
                SceneGroup(
                    id="dashboard-cards",
                    kind="group",
                    area=(64, 470, 952, 260),
                    children=[
                        "dashboard-card-one",
                        "dashboard-card-two",
                        "dashboard-card-three",
                        "metric-one",
                        "metric-two",
                        "metric-three",
                        "label-one",
                        "label-two",
                        "label-three",
                    ],
                ),
                SceneGroup(
                    id="dashboard-progress",
                    kind="frame",
                    area=(64, 828, 952, 244),
                    children=[
                        "dashboard-rail",
                        "dashboard-progress-one",
                        "dashboard-progress-two",
                        "dashboard-progress-three",
                        "dashboard-endpoint",
                        "stage-one",
                        "stage-two",
                        "stage-three",
                    ],
                ),
                SceneGroup(
                    id="dashboard-footer",
                    kind="group",
                    area=(64, 1166, 952, 116),
                    children=["dashboard-bottom-rule", "source", "logo"],
                ),
            ],
        ),
    )


def data_evidence_package(ir: BrandIR) -> TemplatePackage:
    """Compila três modos distintos de apresentar informação confirmada."""
    style = derive_style_system(ir)
    layouts = (_metric_layout(ir), _comparison_layout(ir), _dashboard_layout(ir))
    samples = {
        "evidence-hero-metric-post-4x5": {
            "kicker": "Evidência em contexto",
            "period": "Leitura · 2026",
            "headline": "Um número só importa quando explica uma mudança.",
            "metric": "82%",
            "delta": "+18 pontos",
            "body": "A leitura principal ganha escala; o contexto e a origem dos dados permanecem visíveis.",
            "label-one": "Resultado atual",
            "label-two": "Período anterior",
            "label-three": "Ponto de partida",
            "source": "Fonte: pesquisa própria · base confirmada pelo usuário.",
            "signature": "@sua-marca",
        },
        "evidence-comparison-post-4x5": {
            "kicker": "Comparação direta",
            "headline": "Duas leituras tornam a diferença visível.",
            "label-left": "Antes",
            "label-right": "Depois",
            "value-left": "34%",
            "value-right": "71%",
            "body-left": "Cenário inicial com a mesma definição e a mesma base de leitura.",
            "body-right": "Resultado posterior medido sob os mesmos critérios.",
            "verdict": "A variação aparece sem esconder método, período ou contexto.",
            "source": "Fonte e metodologia informadas pelo usuário.",
        },
        "evidence-dashboard-post-4x5": {
            "kicker": "Três sinais, uma leitura",
            "period": "Ciclo · 03",
            "headline": "O conjunto revela o movimento.",
            "body": "Um painel editorial para métricas relacionadas, sem aparência de dashboard genérico.",
            "metric-one": "48",
            "metric-two": "73%",
            "metric-three": "2,4×",
            "label-one": "Ocorrências confirmadas",
            "label-two": "Adesão no período",
            "label-three": "Variação acumulada",
            "stage-one": "Ponto de partida",
            "stage-two": "Mudança observada",
            "stage-three": "Resultado atual",
            "source": "Fonte: base validada · atualização mais recente.",
        },
    }
    intents = {
        "evidence-hero-metric-post-4x5": (
            "Métrica em primeiro plano",
            "Dar escala a um resultado principal sem separar o número de sua explicação e fonte.",
        ),
        "evidence-comparison-post-4x5": (
            "Comparação lado a lado",
            "Contrastar dois estados equivalentes com hierarquia simétrica e conclusão explícita.",
        ),
        "evidence-dashboard-post-4x5": (
            "Painel modular",
            "Relacionar três indicadores e uma progressão numa composição editorial densa e legível.",
        ),
    }
    compositions = [
        TemplateComposition(
            id=layout.id,
            name_pt=intents[layout.id][0],
            intent_pt=intents[layout.id][1],
            layout=layout,
            sample_content_pt=samples[layout.id],
            critical_nodes=["headline", "logo"],
            export_support=ExportSupport(pptx="native"),
        )
        for layout in layouts
    ]
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Dados e evidências",
        title_pt="Dados e evidências",
        description_pt=(
            "Métricas, comparações e progressões editoriais com fonte, contexto e elementos "
            "gráficos preservados como camadas editáveis."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
