"""Família de mockups editáveis para produtos e interfaces digitais."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "device-mockup"
PACKAGE_VERSION = "1.0.0"


def _phone_layout(ir: BrandIR) -> LayoutSpec:
    layout_id = "device-phone-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Mockup de dispositivo — Celular editorial",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=template_ref(PACKAGE_ID, PACKAGE_VERSION, layout_id),
        locked_layers=[
            ShapeLayer(
                id="phone-stage",
                shape="rectangle",
                area=(488, 154, 548, 1034),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="phone-body",
                shape="rectangle",
                area=(548, 214, 430, 880),
                color_token="color.text",
                opacity=0.94,
                z_index=2,
            ),
            ShapeLayer(
                id="phone-bezel",
                shape="rectangle",
                area=(562, 228, 402, 852),
                color_token="color.background",
                z_index=3,
            ),
            ShapeLayer(
                id="phone-camera",
                shape="circle",
                area=(745, 244, 36, 36),
                color_token="color.text",
                z_index=5,
            ),
            ShapeLayer(
                id="phone-home",
                shape="rectangle",
                area=(704, 1048, 118, 5),
                color_token="color.text",
                opacity=0.72,
                z_index=5,
            ),
            ShapeLayer(
                id="phone-cta-field",
                shape="rectangle",
                area=(72, 764, 332, 78),
                color_token="color.primary",
                opacity=0.16,
                z_index=1,
            ),
            ShapeLayer(
                id="phone-bottom-rule",
                shape="rectangle",
                area=(72, 1174, 964, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(72, 78, 410, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=50,
                area=(72, 238, 380, 262),
                fit="fixed",
                font_size_px=54,
                font_weight=690,
                line_height=0.92,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=112,
                area=(72, 554, 360, 150),
                fit="fixed",
                required=False,
                font_size_px=20,
                line_height=1.32,
                z_index=10,
            ),
            Slot(
                id="cta",
                kind="text",
                role="caption",
                max_chars=32,
                area=(94, 788, 288, 30),
                fit="fixed",
                font_size_px=14,
                font_weight=700,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(776, 1480),
                area=(576, 292, 374, 740),
                fit="fixed",
                required=False,
                z_index=4,
            ),
            Slot(
                id="caption",
                kind="text",
                role="caption",
                max_chars=54,
                area=(548, 1120, 430, 38),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="center",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(72, 1216, 470, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (852, 1168, 100, 100)),
        ],
        scene_graph=SceneGraph(
            roots=["phone-root"],
            groups=[
                SceneGroup(
                    id="phone-root",
                    kind="group",
                    area=(72, 78, 964, 1214),
                    children=["phone-copy", "phone-device", "phone-footer"],
                ),
                SceneGroup(
                    id="phone-copy",
                    kind="stack",
                    direction="vertical",
                    gap_px=46,
                    area=(72, 78, 380, 764),
                    children=["kicker", "headline", "body", "phone-cta-field", "cta"],
                ),
                SceneGroup(
                    id="phone-device",
                    kind="frame",
                    area=(488, 154, 548, 1004),
                    clip=False,
                    children=[
                        "phone-stage",
                        "phone-body",
                        "phone-bezel",
                        "phone-camera",
                        "phone-home",
                        "photo",
                        "caption",
                    ],
                ),
                SceneGroup(
                    id="phone-footer",
                    kind="group",
                    area=(72, 1174, 964, 118),
                    children=["phone-bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def _browser_layout(ir: BrandIR) -> LayoutSpec:
    layout_id = "device-browser-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Mockup de dispositivo — Janela de navegador",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=template_ref(PACKAGE_ID, PACKAGE_VERSION, layout_id),
        locked_layers=[
            ShapeLayer(
                id="browser-shadow",
                shape="rectangle",
                area=(104, 458, 900, 620),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="browser-frame",
                shape="rectangle",
                area=(76, 430, 900, 620),
                color_token="color.text",
                opacity=0.94,
                z_index=2,
            ),
            ShapeLayer(
                id="browser-screen-field",
                shape="rectangle",
                area=(82, 498, 888, 546),
                color_token="color.background",
                z_index=3,
            ),
            ShapeLayer(
                id="browser-chrome",
                shape="rectangle",
                area=(82, 436, 888, 62),
                color_token="color.primary",
                opacity=0.12,
                z_index=3,
            ),
            ShapeLayer(
                id="browser-dot-one",
                shape="circle",
                area=(106, 457, 16, 16),
                color_token="color.primary",
                z_index=4,
            ),
            ShapeLayer(
                id="browser-dot-two",
                shape="circle",
                area=(134, 457, 16, 16),
                color_token="color.primary",
                opacity=0.62,
                z_index=4,
            ),
            ShapeLayer(
                id="browser-dot-three",
                shape="circle",
                area=(162, 457, 16, 16),
                color_token="color.primary",
                opacity=0.3,
                z_index=4,
            ),
            ShapeLayer(
                id="browser-address",
                shape="rectangle",
                area=(220, 450, 636, 30),
                color_token="color.background",
                opacity=0.9,
                z_index=4,
            ),
            ShapeLayer(
                id="browser-bottom-rule",
                shape="rectangle",
                area=(76, 1166, 928, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 72, 430, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=28,
                area=(690, 72, 314, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=54,
                area=(76, 142, 668, 182),
                fit="fixed",
                font_size_px=62,
                font_weight=690,
                line_height=0.94,
                letter_spacing_em=-0.045,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=96,
                area=(762, 164, 242, 138),
                fit="fixed",
                required=False,
                font_size_px=17,
                line_height=1.35,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="url",
                kind="text",
                role="caption",
                max_chars=60,
                area=(240, 456, 596, 20),
                fit="fixed",
                required=False,
                font_size_px=12,
                opacity=0.72,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1776, 1092),
                area=(82, 498, 888, 546),
                fit="fixed",
                required=False,
                z_index=4,
            ),
            Slot(
                id="caption",
                kind="text",
                role="caption",
                max_chars=72,
                area=(76, 1092, 692, 46),
                fit="fixed",
                required=False,
                font_size_px=13,
                line_height=1.3,
                z_index=10,
            ),
            logo_slot(ir, (824, 1168, 100, 100)),
        ],
        scene_graph=SceneGraph(
            roots=["browser-root"],
            groups=[
                SceneGroup(
                    id="browser-root",
                    kind="frame",
                    area=(76, 72, 928, 1206),
                    children=["browser-header", "browser-window", "browser-footer"],
                ),
                SceneGroup(
                    id="browser-header",
                    kind="grid",
                    columns=2,
                    gap_px=72,
                    area=(76, 72, 928, 252),
                    children=["kicker", "issue", "headline", "body"],
                ),
                SceneGroup(
                    id="browser-window",
                    kind="frame",
                    area=(76, 430, 928, 648),
                    clip=False,
                    children=[
                        "browser-shadow",
                        "browser-frame",
                        "browser-screen-field",
                        "browser-chrome",
                        "browser-dot-one",
                        "browser-dot-two",
                        "browser-dot-three",
                        "browser-address",
                        "url",
                        "photo",
                    ],
                ),
                SceneGroup(
                    id="browser-footer",
                    kind="group",
                    area=(76, 1092, 928, 186),
                    children=["caption", "browser-bottom-rule", "logo"],
                ),
            ],
        ),
    )


def _ecosystem_layout(ir: BrandIR) -> LayoutSpec:
    layout_id = "device-ecosystem-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Mockup de dispositivo — Ecossistema de telas",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=template_ref(PACKAGE_ID, PACKAGE_VERSION, layout_id),
        locked_layers=[
            ShapeLayer(
                id="ecosystem-orbit",
                shape="circle",
                area=(410, 210, 560, 560),
                color_token="color.primary",
                opacity=0.08,
                z_index=0,
            ),
            ShapeLayer(
                id="ecosystem-tablet-body",
                shape="rectangle",
                area=(230, 402, 742, 508),
                color_token="color.text",
                opacity=0.94,
                z_index=2,
            ),
            ShapeLayer(
                id="ecosystem-tablet-screen",
                shape="rectangle",
                area=(248, 420, 706, 472),
                color_token="color.background",
                z_index=3,
            ),
            ShapeLayer(
                id="ecosystem-tablet-camera",
                shape="circle",
                area=(934, 640, 9, 9),
                color_token="color.text",
                z_index=5,
            ),
            ShapeLayer(
                id="ecosystem-phone-shadow",
                shape="rectangle",
                area=(120, 666, 278, 546),
                color_token="color.primary",
                opacity=0.12,
                z_index=4,
            ),
            ShapeLayer(
                id="ecosystem-phone-body",
                shape="rectangle",
                area=(96, 642, 278, 546),
                color_token="color.text",
                opacity=0.96,
                z_index=5,
            ),
            ShapeLayer(
                id="ecosystem-phone-screen",
                shape="rectangle",
                area=(108, 680, 254, 466),
                color_token="color.background",
                z_index=6,
            ),
            ShapeLayer(
                id="ecosystem-phone-camera",
                shape="circle",
                area=(221, 655, 28, 28),
                color_token="color.background",
                z_index=7,
            ),
            ShapeLayer(
                id="ecosystem-cta-field",
                shape="rectangle",
                area=(648, 1016, 328, 78),
                color_token="color.primary",
                opacity=0.16,
                z_index=1,
            ),
            ShapeLayer(
                id="ecosystem-bottom-rule",
                shape="rectangle",
                area=(76, 1178, 900, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 68, 420, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=50,
                area=(76, 130, 620, 154),
                fit="fixed",
                font_size_px=54,
                font_weight=690,
                line_height=0.94,
                letter_spacing_em=-0.04,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=86,
                area=(720, 130, 256, 132),
                fit="fixed",
                required=False,
                font_size_px=17,
                line_height=1.35,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="photo-primary",
                kind="image",
                min_resolution=(1412, 944),
                area=(248, 420, 706, 472),
                fit="fixed",
                required=False,
                z_index=4,
            ),
            Slot(
                id="photo-secondary",
                kind="image",
                min_resolution=(508, 932),
                area=(108, 680, 254, 466),
                fit="fixed",
                required=False,
                z_index=7,
            ),
            Slot(
                id="caption",
                kind="text",
                role="caption",
                max_chars=64,
                area=(424, 936, 552, 46),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                line_height=1.3,
                z_index=10,
            ),
            Slot(
                id="cta",
                kind="text",
                role="caption",
                max_chars=32,
                area=(670, 1040, 284, 30),
                fit="fixed",
                font_size_px=14,
                font_weight=700,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 1218, 460, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (876, 1168, 100, 100)),
        ],
        scene_graph=SceneGraph(
            roots=["ecosystem-root"],
            groups=[
                SceneGroup(
                    id="ecosystem-root",
                    kind="stack",
                    direction="vertical",
                    gap_px=54,
                    area=(76, 68, 900, 1224),
                    children=["ecosystem-header", "ecosystem-devices", "ecosystem-close"],
                ),
                SceneGroup(
                    id="ecosystem-header",
                    kind="stack",
                    direction="vertical",
                    gap_px=32,
                    area=(76, 68, 900, 216),
                    children=["kicker", "headline", "body"],
                ),
                SceneGroup(
                    id="ecosystem-devices",
                    kind="stack",
                    direction="horizontal",
                    gap_px=0,
                    area=(96, 210, 880, 1002),
                    children=[
                        "ecosystem-orbit",
                        "ecosystem-tablet-body",
                        "ecosystem-tablet-screen",
                        "ecosystem-tablet-camera",
                        "photo-primary",
                        "ecosystem-phone-shadow",
                        "ecosystem-phone-body",
                        "ecosystem-phone-screen",
                        "ecosystem-phone-camera",
                        "photo-secondary",
                        "caption",
                    ],
                ),
                SceneGroup(
                    id="ecosystem-close",
                    kind="stack",
                    direction="horizontal",
                    gap_px=28,
                    area=(76, 1016, 900, 276),
                    children=[
                        "ecosystem-cta-field",
                        "cta",
                        "ecosystem-bottom-rule",
                        "signature",
                        "logo",
                    ],
                ),
            ],
        ),
    )


def device_mockup_package(ir: BrandIR) -> TemplatePackage:
    """Compila três estruturas de dispositivo sem rasterizar a moldura."""
    style = derive_style_system(ir)
    layouts = (_phone_layout(ir), _browser_layout(ir), _ecosystem_layout(ir))
    samples = {
        "device-phone-post-4x5": {
            "kicker": "Produto digital em contexto",
            "headline": "A interface também carrega a voz da marca.",
            "body": "Apresente uma tela real dentro de uma composição que continua completamente editável.",
            "cta": "Conheça a experiência",
            "caption": "Tela principal · versão demonstrada",
            "signature": "@sua-marca",
        },
        "device-browser-post-4x5": {
            "kicker": "Experiência em tela ampla",
            "issue": "Versão · 01",
            "headline": "Mostre o produto sem esconder o projeto.",
            "body": "A janela organiza contexto, interface e legenda como uma peça editorial.",
            "url": "produto.exemplo/interface",
            "caption": "Substitua a imagem pela captura real do site, sistema ou protótipo.",
        },
        "device-ecosystem-post-4x5": {
            "kicker": "Uma experiência, várias escalas",
            "headline": "Continuidade entre telas.",
            "body": "Duas capturas independentes demonstram adaptação, não apenas redução.",
            "caption": "Interface ampla e detalhe móvel apresentados na mesma narrativa.",
            "cta": "Ver o sistema completo",
            "signature": "@sua-marca",
        },
    }
    intents = {
        "device-phone-post-4x5": (
            "Celular editorial",
            "Apresentar uma captura vertical com argumento, legenda e CTA sem fundir a tela ao mockup.",
        ),
        "device-browser-post-4x5": (
            "Janela de navegador",
            "Enquadrar um site ou sistema em uma janela ampla com contexto editorial e endereço editável.",
        ),
        "device-ecosystem-post-4x5": (
            "Ecossistema de telas",
            "Relacionar capturas desktop e móvel numa composição sobreposta que evidencia continuidade.",
        ),
    }
    compositions = []
    for layout in layouts:
        overlaps = []
        if layout.id == "device-ecosystem-post-4x5":
            overlaps = [("photo-primary", "photo-secondary")]
        compositions.append(
            TemplateComposition(
                id=layout.id,
                name_pt=intents[layout.id][0],
                intent_pt=intents[layout.id][1],
                layout=layout,
                sample_content_pt=samples[layout.id],
                critical_nodes=["headline", "logo"],
                allowed_overlaps=overlaps,
                export_support=ExportSupport(pptx="native"),
            )
        )
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Mockup de dispositivo",
        title_pt="Mockup de dispositivo",
        description_pt=(
            "Celular, navegador e ecossistema de telas com molduras nativas, capturas substituíveis "
            "e toda a composição preservada para edição."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
