"""Família editorial de moda: capa, coleção e retrato legendado."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "fashion-editorial"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _cover(ir: BrandIR) -> LayoutSpec:
    layout_id = "fashion-cover-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Editorial de moda — Capa de ateliê",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="portrait-mat",
                shape="rectangle",
                area=(214, 168, 784, 822),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="portrait-shadow",
                shape="rectangle",
                area=(232, 188, 766, 802),
                color_token="color.text",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="masthead-rule",
                shape="rectangle",
                area=(76, 136, 922, 2),
                color_token="color.text",
                opacity=0.34,
                z_index=2,
            ),
            ShapeLayer(
                id="closing-rule",
                shape="rectangle",
                area=(76, 1214, 922, 2),
                color_token="color.text",
                opacity=0.34,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=48,
                area=(76, 76, 432, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=28,
                area=(690, 76, 308, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=650,
                text_align="right",
                text_transform="uppercase",
                letter_spacing_em=0.14,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1532, 1604),
                area=(232, 188, 766, 802),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=32,
                area=(76, 812, 864, 280),
                fit="fixed",
                font_size_px=118,
                font_weight=760,
                line_height=0.86,
                letter_spacing_em=-0.055,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=108,
                area=(76, 1110, 572, 78),
                fit="fixed",
                required=False,
                font_size_px=21,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 1240, 476, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.05,
                z_index=10,
            ),
            logo_slot(ir, (866, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["cover-root"],
            groups=[
                SceneGroup(
                    id="cover-root",
                    kind="frame",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "portrait-stack",
                        "masthead-rule",
                        "closing-rule",
                        "masthead-row",
                        "story-stack",
                        "signature",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="portrait-stack",
                    kind="frame",
                    area=(214, 168, 784, 822),
                    children=["portrait-mat", "portrait-shadow", "photo"],
                ),
                SceneGroup(
                    id="masthead-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=182,
                    area=(76, 76, 922, 34),
                    children=["kicker", "issue"],
                ),
                SceneGroup(
                    id="story-stack",
                    kind="stack",
                    direction="vertical",
                    gap_px=18,
                    area=(76, 812, 864, 376),
                    children=["headline", "body"],
                ),
            ],
        ),
    )


def _spread(ir: BrandIR) -> LayoutSpec:
    layout_id = "fashion-spread-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Editorial de moda — Página de coleção",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="left-photo-mat",
                shape="rectangle",
                area=(74, 242, 410, 650),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="right-photo-mat",
                shape="rectangle",
                area=(594, 120, 412, 528),
                color_token="color.text",
                opacity=0.1,
                z_index=1,
            ),
            ShapeLayer(
                id="collection-index-field",
                shape="rectangle",
                area=(594, 702, 412, 190),
                color_token="color.primary",
                z_index=1,
            ),
            ShapeLayer(
                id="footer-rule",
                shape="rectangle",
                area=(74, 1190, 932, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(74, 72, 410, 32),
                fit="fixed",
                required=False,
                font_size_px=13,
                letter_spacing_em=0.08,
                z_index=10,
            ),
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(594, 72, 412, 32),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_align="right",
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="photo-primary",
                kind="image",
                min_resolution=(820, 1300),
                area=(74, 242, 410, 650),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="photo-secondary",
                kind="image",
                min_resolution=(824, 1056),
                area=(594, 120, 412, 528),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=3,
                area=(624, 724, 352, 142),
                fit="fixed",
                font_size_px=126,
                font_weight=600,
                line_height=0.84,
                text_align="right",
                letter_spacing_em=-0.055,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=36,
                area=(74, 942, 642, 220),
                fit="fixed",
                font_size_px=94,
                font_weight=700,
                line_height=0.9,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=104,
                area=(752, 964, 254, 168),
                fit="fixed",
                required=False,
                font_size_px=20,
                line_height=1.22,
                text_align="right",
                z_index=10,
            ),
            logo_slot(ir, (874, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["spread-root"],
            groups=[
                SceneGroup(
                    id="spread-root",
                    kind="grid",
                    columns=2,
                    gap_px=110,
                    area=(74, 72, 932, 1266),
                    children=["meta-row", "left-column", "right-column", "footer-rule", "logo"],
                ),
                SceneGroup(
                    id="meta-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=110,
                    area=(74, 72, 932, 32),
                    children=["signature", "kicker"],
                ),
                SceneGroup(
                    id="left-column",
                    kind="stack",
                    direction="vertical",
                    gap_px=50,
                    area=(74, 242, 642, 920),
                    children=["left-photo-mat", "photo-primary", "headline"],
                ),
                SceneGroup(
                    id="right-column",
                    kind="stack",
                    direction="vertical",
                    gap_px=54,
                    area=(594, 120, 412, 1012),
                    children=[
                        "right-photo-mat",
                        "photo-secondary",
                        "collection-index-field",
                        "index",
                        "body",
                    ],
                ),
            ],
        ),
    )


def _portrait(ir: BrandIR) -> LayoutSpec:
    layout_id = "fashion-portrait-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Editorial de moda — Retrato com legenda",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="portrait-backdrop",
                shape="rectangle",
                area=(326, 88, 672, 830),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="editorial-rail",
                shape="rectangle",
                area=(74, 88, 2, 1108),
                color_token="color.text",
                opacity=0.42,
                z_index=2,
            ),
            ShapeLayer(
                id="caption-marker",
                shape="rectangle",
                area=(118, 744, 132, 8),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="headline-field",
                shape="rectangle",
                area=(250, 860, 748, 242),
                color_token="color.background",
                z_index=4,
            ),
            ShapeLayer(
                id="bottom-rule",
                shape="rectangle",
                area=(74, 1210, 924, 2),
                color_token="color.text",
                opacity=0.32,
                z_index=2,
            ),
            ShapeLayer(
                id="folio-disc",
                shape="circle",
                area=(118, 1028, 38, 38),
                color_token="color.primary",
                z_index=3,
            ),
        ],
        slots=[
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1344, 1660),
                area=(326, 88, 672, 830),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=24,
                area=(118, 90, 132, 98),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=650,
                line_height=1.5,
                text_transform="uppercase",
                letter_spacing_em=0.16,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(104, 286, 180, 166),
                fit="fixed",
                font_size_px=148,
                font_weight=500,
                line_height=0.84,
                letter_spacing_em=-0.06,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(118, 776, 168, 104),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_style="italic",
                line_height=1.3,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=34,
                area=(276, 888, 692, 188),
                fit="fixed",
                font_size_px=86,
                font_weight=720,
                line_height=0.9,
                letter_spacing_em=-0.045,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=96,
                area=(326, 1118, 486, 78),
                fit="fixed",
                required=False,
                font_size_px=20,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(74, 1240, 474, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                letter_spacing_em=0.08,
                z_index=10,
            ),
            logo_slot(ir, (866, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["portrait-root"],
            groups=[
                SceneGroup(
                    id="portrait-root",
                    kind="group",
                    area=(0, 0, 1080, 1350),
                    children=["portrait-frame", "editorial-column", "message-frame", "footer-row"],
                ),
                SceneGroup(
                    id="portrait-frame",
                    kind="frame",
                    area=(326, 88, 672, 830),
                    children=["portrait-backdrop", "photo"],
                ),
                SceneGroup(
                    id="editorial-column",
                    kind="stack",
                    direction="vertical",
                    gap_px=92,
                    area=(74, 88, 212, 1108),
                    children=[
                        "editorial-rail",
                        "issue",
                        "index",
                        "caption-marker",
                        "kicker",
                        "folio-disc",
                    ],
                ),
                SceneGroup(
                    id="message-frame",
                    kind="frame",
                    area=(250, 860, 748, 336),
                    children=["headline-field", "headline", "body"],
                ),
                SceneGroup(
                    id="footer-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=318,
                    area=(74, 1172, 924, 132),
                    children=["bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def fashion_editorial_package(ir: BrandIR) -> TemplatePackage:
    """Publica três arquiteturas fotográficas preservando edição completa."""
    style = derive_style_system(ir)
    layouts = (_cover(ir), _spread(ir), _portrait(ir))
    samples = {
        "fashion-cover-post-4x5": {
            "kicker": "Caderno de formas",
            "issue": "Edição 01 · 2026",
            "headline": "Forma que permanece.",
            "body": "Uma leitura de matéria, gesto e presença.",
            "signature": "@sua-marca",
        },
        "fashion-spread-post-4x5": {
            "signature": "@sua-marca",
            "kicker": "Coleção em movimento",
            "index": "2",
            "headline": "Entre ritmo e matéria.",
            "body": "Duas imagens constroem uma narrativa em contraponto.",
        },
        "fashion-portrait-post-4x5": {
            "issue": "Caderno\n01",
            "index": "3",
            "kicker": "Retrato, gesto e detalhe",
            "headline": "Uma presença ocupa a página.",
            "body": "A legenda dá contexto sem disputar atenção com a imagem.",
            "signature": "@sua-marca",
        },
    }
    intents = {
        "fashion-cover-post-4x5": (
            "Capa de ateliê",
            "Sobrepor uma manchete ampla a um retrato deslocado, como uma capa autoral.",
        ),
        "fashion-spread-post-4x5": (
            "Página de coleção",
            "Articular duas imagens de proporções diferentes com índice e texto editorial.",
        ),
        "fashion-portrait-post-4x5": (
            "Retrato com legenda",
            "Criar uma página vertical com trilho de metadados, retrato e legenda sobreposta.",
        ),
    }
    compositions = []
    for layout in layouts:
        name, intent = intents[layout.id]
        compositions.append(
            TemplateComposition(
                id=layout.id,
                name_pt=name,
                intent_pt=intent,
                layout=layout,
                sample_content_pt=samples[layout.id],
                critical_nodes=["headline", "logo"],
                export_support=ExportSupport(pptx="native"),
            )
        )
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Editorial de moda",
        title_pt="Editorial de moda",
        description_pt=(
            "Três composições fotográficas editáveis para capa, coleção e narrativa de retrato."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
