"""Família de tipografia cinética: eco, corte e pulso sequencial."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "kinetic-typography"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _echo(ir: BrandIR) -> LayoutSpec:
    layout_id = "kinetic-echo-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Tipografia cinética — Eco progressivo",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="speed-bar-short",
                shape="rectangle",
                area=(82, 270, 208, 12),
                color_token="color.primary",
                opacity=0.32,
                z_index=2,
            ),
            ShapeLayer(
                id="speed-bar-medium",
                shape="rectangle",
                area=(82, 296, 424, 12),
                color_token="color.primary",
                opacity=0.62,
                z_index=2,
            ),
            ShapeLayer(
                id="speed-bar-long",
                shape="rectangle",
                area=(82, 322, 704, 12),
                color_token="color.primary",
                z_index=2,
            ),
            ShapeLayer(
                id="end-stop",
                shape="rectangle",
                area=(974, 322, 24, 716),
                color_token="color.primary",
                z_index=2,
            ),
            ShapeLayer(
                id="footer-rule",
                shape="rectangle",
                area=(82, 1198, 916, 4),
                color_token="color.text",
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=52,
                area=(82, 82, 512, 38),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_weight=700,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(704, 82, 294, 38),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=700,
                text_align="right",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            Slot(
                id="echo-far",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=18,
                area=(82, 380, 780, 150),
                fit="fixed",
                required=False,
                opacity=0.16,
                font_size_px=126,
                font_weight=850,
                line_height=0.86,
                letter_spacing_em=-0.055,
                text_transform="uppercase",
                z_index=6,
            ),
            Slot(
                id="echo-near",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=18,
                area=(142, 512, 780, 150),
                fit="fixed",
                required=False,
                opacity=0.46,
                font_size_px=126,
                font_weight=850,
                line_height=0.86,
                letter_spacing_em=-0.055,
                text_transform="uppercase",
                z_index=7,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=18,
                area=(202, 644, 720, 166),
                fit="fixed",
                font_size_px=132,
                font_weight=900,
                line_height=0.86,
                letter_spacing_em=-0.06,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=128,
                area=(202, 870, 588, 152),
                fit="fixed",
                required=False,
                font_size_px=25,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(82, 1032, 300, 142),
                fit="fixed",
                font_size_px=112,
                font_weight=850,
                line_height=0.86,
                letter_spacing_em=-0.06,
                text_format="zero-padded",
                z_index=10,
            ),
            logo_slot(ir, (856, 1158, 142, 142)),
        ],
        scene_graph=SceneGraph(
            roots=["echo-root"],
            groups=[
                SceneGroup(
                    id="echo-root",
                    kind="frame",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "speed-bars",
                        "end-stop",
                        "footer-rule",
                        "meta-row",
                        "echo-stack",
                        "body",
                        "index",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="speed-bars",
                    kind="stack",
                    direction="vertical",
                    gap_px=14,
                    area=(82, 270, 704, 64),
                    children=["speed-bar-short", "speed-bar-medium", "speed-bar-long"],
                ),
                SceneGroup(
                    id="meta-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=110,
                    area=(82, 82, 916, 38),
                    children=["kicker", "signature"],
                ),
                SceneGroup(
                    id="echo-stack",
                    kind="stack",
                    direction="vertical",
                    gap_px=0,
                    area=(82, 380, 840, 430),
                    children=["echo-far", "echo-near", "headline"],
                ),
            ],
        ),
    )


def _split(ir: BrandIR) -> LayoutSpec:
    layout_id = "kinetic-split-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Tipografia cinética — Corte em aceleração",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="upper-field",
                shape="rectangle",
                area=(0, 0, 1080, 412),
                color_token="color.primary",
                z_index=1,
            ),
            ShapeLayer(
                id="cut-bar-one",
                shape="rectangle",
                area=(80, 470, 668, 24),
                color_token="color.primary",
                z_index=2,
            ),
            ShapeLayer(
                id="cut-bar-two",
                shape="rectangle",
                area=(244, 516, 758, 24),
                color_token="color.primary",
                opacity=0.56,
                z_index=2,
            ),
            ShapeLayer(
                id="cut-bar-three",
                shape="rectangle",
                area=(448, 562, 554, 24),
                color_token="color.primary",
                opacity=0.24,
                z_index=2,
            ),
            ShapeLayer(
                id="counter-field",
                shape="rectangle",
                area=(80, 970, 922, 184),
                color_token="color.text",
                z_index=1,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                color_token="color.background",
                max_chars=48,
                area=(80, 72, 490, 36),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_weight=700,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="headline-lead",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=16,
                area=(80, 142, 840, 188),
                fit="fixed",
                required=False,
                font_size_px=142,
                font_weight=900,
                line_height=0.86,
                letter_spacing_em=-0.065,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=24,
                area=(244, 638, 758, 250),
                fit="fixed",
                font_size_px=116,
                font_weight=880,
                line_height=0.87,
                letter_spacing_em=-0.06,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.background",
                max_chars=3,
                area=(104, 992, 186, 134),
                fit="fixed",
                font_size_px=100,
                font_weight=850,
                line_height=0.86,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                color_token="color.background",
                max_chars=118,
                area=(350, 998, 526, 122),
                fit="fixed",
                required=False,
                font_size_px=24,
                font_weight=550,
                line_height=1.18,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(80, 1210, 446, 38),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=700,
                letter_spacing_em=0.05,
                z_index=10,
            ),
            logo_slot(ir, (860, 1158, 142, 142)),
        ],
        scene_graph=SceneGraph(
            roots=["split-root"],
            groups=[
                SceneGroup(
                    id="split-root",
                    kind="group",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "upper-field",
                        "cut-bars",
                        "counter-field",
                        "upper-message",
                        "headline",
                        "counter-row",
                        "signature",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="cut-bars",
                    kind="stack",
                    direction="vertical",
                    gap_px=22,
                    area=(80, 470, 922, 116),
                    children=["cut-bar-one", "cut-bar-two", "cut-bar-three"],
                ),
                SceneGroup(
                    id="upper-message",
                    kind="stack",
                    direction="vertical",
                    gap_px=34,
                    area=(80, 72, 840, 258),
                    children=["kicker", "headline-lead"],
                ),
                SceneGroup(
                    id="counter-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=60,
                    area=(104, 992, 772, 134),
                    children=["index", "body"],
                ),
            ],
        ),
    )


def _pulse(ir: BrandIR) -> LayoutSpec:
    layout_id = "kinetic-pulse-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Tipografia cinética — Pulso sequencial",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="pulse-dot-one",
                shape="circle",
                area=(82, 214, 38, 38),
                color_token="color.primary",
                opacity=0.32,
                z_index=2,
            ),
            ShapeLayer(
                id="pulse-dot-two",
                shape="circle",
                area=(82, 476, 64, 64),
                color_token="color.primary",
                opacity=0.64,
                z_index=2,
            ),
            ShapeLayer(
                id="pulse-dot-three",
                shape="circle",
                area=(82, 764, 94, 94),
                color_token="color.primary",
                z_index=2,
            ),
            ShapeLayer(
                id="pulse-line-one",
                shape="rectangle",
                area=(222, 250, 304, 5),
                color_token="color.primary",
                opacity=0.28,
                z_index=2,
            ),
            ShapeLayer(
                id="pulse-line-two",
                shape="rectangle",
                area=(222, 540, 516, 7),
                color_token="color.primary",
                opacity=0.58,
                z_index=2,
            ),
            ShapeLayer(
                id="pulse-line-three",
                shape="rectangle",
                area=(222, 858, 776, 10),
                color_token="color.primary",
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=48,
                area=(82, 78, 520, 38),
                fit="fixed",
                required=False,
                font_size_px=15,
                font_weight=700,
                text_transform="uppercase",
                letter_spacing_em=0.18,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(704, 78, 294, 38),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=700,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="pulse-one",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=14,
                area=(222, 154, 600, 104),
                fit="fixed",
                required=False,
                opacity=0.34,
                font_size_px=78,
                font_weight=800,
                line_height=0.9,
                letter_spacing_em=-0.04,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="pulse-two",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=14,
                area=(222, 398, 700, 140),
                fit="fixed",
                required=False,
                opacity=0.68,
                font_size_px=104,
                font_weight=840,
                line_height=0.88,
                letter_spacing_em=-0.05,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=20,
                area=(222, 672, 776, 184),
                fit="fixed",
                font_size_px=142,
                font_weight=900,
                line_height=0.84,
                letter_spacing_em=-0.065,
                text_transform="uppercase",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=132,
                area=(222, 936, 596, 146),
                fit="fixed",
                required=False,
                font_size_px=25,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(82, 1092, 304, 142),
                fit="fixed",
                font_size_px=112,
                font_weight=850,
                line_height=0.86,
                text_format="zero-padded",
                z_index=10,
            ),
            logo_slot(ir, (856, 1158, 142, 142)),
        ],
        scene_graph=SceneGraph(
            roots=["pulse-root"],
            groups=[
                SceneGroup(
                    id="pulse-root",
                    kind="grid",
                    columns=2,
                    gap_px=46,
                    area=(82, 78, 916, 1230),
                    children=[
                        "pulse-rail",
                        "type-sequence",
                        "body",
                        "index",
                        "meta-row",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="pulse-rail",
                    kind="stack",
                    direction="vertical",
                    gap_px=198,
                    area=(82, 214, 916, 654),
                    children=[
                        "pulse-dot-one",
                        "pulse-line-one",
                        "pulse-dot-two",
                        "pulse-line-two",
                        "pulse-dot-three",
                        "pulse-line-three",
                    ],
                ),
                SceneGroup(
                    id="type-sequence",
                    kind="stack",
                    direction="vertical",
                    gap_px=112,
                    area=(222, 154, 776, 702),
                    children=["pulse-one", "pulse-two", "headline"],
                ),
                SceneGroup(
                    id="meta-row",
                    kind="stack",
                    direction="horizontal",
                    gap_px=102,
                    area=(82, 78, 916, 38),
                    children=["kicker", "signature"],
                ),
            ],
        ),
    )


def kinetic_typography_package(ir: BrandIR) -> TemplatePackage:
    """Publica três sequências tipográficas inteiramente editáveis."""
    style = derive_style_system(ir)
    layouts = (_echo(ir), _split(ir), _pulse(ir))
    samples = {
        "kinetic-echo-post-4x5": {
            "kicker": "Movimento tipográfico",
            "signature": "@sua-marca",
            "echo-far": "Avance",
            "echo-near": "Avance",
            "headline": "Avance",
            "body": "A repetição cria direção, memória e velocidade dentro do mesmo quadro.",
            "index": "1",
        },
        "kinetic-split-post-4x5": {
            "kicker": "Uma ideia em duas velocidades",
            "headline-lead": "Mude",
            "headline": "o ritmo agora",
            "index": "2",
            "body": "O corte separa a promessa da resposta e transforma a leitura em ação.",
            "signature": "@sua-marca",
        },
        "kinetic-pulse-post-4x5": {
            "kicker": "Sequência em expansão",
            "signature": "@sua-marca",
            "pulse-one": "Comece",
            "pulse-two": "Continue",
            "headline": "Transforme",
            "body": "Cada estágio amplia a mensagem até ela ocupar o campo inteiro.",
            "index": "3",
        },
    }
    intents = {
        "kinetic-echo-post-4x5": (
            "Eco progressivo",
            "Criar aceleração por repetição deslocada e ganho gradual de presença tipográfica.",
        ),
        "kinetic-split-post-4x5": (
            "Corte em aceleração",
            "Separar a mensagem em dois campos ligados por barras que atravessam o quadro.",
        ),
        "kinetic-pulse-post-4x5": (
            "Pulso sequencial",
            "Construir progressão por três estágios que crescem em escala, peso e alcance.",
        ),
    }
    compositions = []
    for layout in layouts:
        name, intent = intents[layout.id]
        compositions.append(
            TemplateComposition(
                id=layout.id,
                name_pt=name,
                intent_pt=intent,
                layout=layout,
                sample_content_pt=samples[layout.id],
                critical_nodes=["headline", "logo"],
                export_support=ExportSupport(pptx="native"),
            )
        )
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Tipografia cinética",
        title_pt="Tipografia cinética",
        description_pt=(
            "Três composições editáveis em que repetição, corte e progressão sugerem movimento."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
