"""Família de minimalismo de luxo: escala silenciosa, galeria e eixo central."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "minimal-luxury"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _whisper(ir: BrandIR) -> LayoutSpec:
    layout_id = "luxury-whisper-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Minimalismo de luxo — Sussurro monumental",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="whisper-top-rule",
                shape="rectangle",
                area=(76, 76, 928, 2),
                color_token="color.text",
                opacity=0.28,
                z_index=2,
            ),
            ShapeLayer(
                id="whisper-marker",
                shape="circle",
                area=(76, 152, 18, 18),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="whisper-axis",
                shape="rectangle",
                area=(960, 154, 2, 776),
                color_token="color.text",
                opacity=0.22,
                z_index=2,
            ),
            ShapeLayer(
                id="whisper-closing-field",
                shape="rectangle",
                area=(0, 1218, 1080, 132),
                color_token="color.primary",
                z_index=1,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(112, 142, 452, 34),
                fit="fixed",
                required=False,
                font_size_px=14,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.22,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(76, 222, 840, 460),
                fit="fixed",
                font_size_px=402,
                font_weight=500,
                line_height=0.78,
                letter_spacing_em=-0.08,
                opacity=0.12,
                fill_mode="stroke",
                stroke_color_token="color.primary",
                stroke_width_px=2,
                text_format="zero-padded",
                z_index=2,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=38,
                area=(76, 672, 760, 266),
                fit="fixed",
                font_size_px=108,
                font_weight=620,
                line_height=0.9,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=104,
                area=(610, 978, 352, 116),
                fit="fixed",
                required=False,
                font_size_px=21,
                line_height=1.28,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                color_token="color.background",
                max_chars=42,
                area=(76, 1262, 478, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (872, 1070, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["whisper-root"],
            groups=[
                SceneGroup(
                    id="whisper-root",
                    kind="frame",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "whisper-top-rule",
                        "whisper-marker",
                        "whisper-axis",
                        "whisper-closing-field",
                        "upper-whisper",
                        "message-whisper",
                        "body",
                        "signature",
                        "logo",
                    ],
                ),
                SceneGroup(
                    id="upper-whisper",
                    kind="stack",
                    direction="vertical",
                    gap_px=46,
                    area=(76, 142, 840, 540),
                    children=["kicker", "index"],
                ),
                SceneGroup(
                    id="message-whisper",
                    kind="frame",
                    area=(76, 672, 760, 266),
                    children=["headline"],
                ),
            ],
        ),
    )


def _gallery(ir: BrandIR) -> LayoutSpec:
    layout_id = "luxury-gallery-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Minimalismo de luxo — Galeria silenciosa",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="gallery-mat",
                shape="rectangle",
                area=(102, 218, 664, 766),
                color_token="color.primary",
                opacity=0.09,
                z_index=1,
            ),
            ShapeLayer(
                id="gallery-shadow",
                shape="rectangle",
                area=(120, 236, 646, 748),
                color_token="color.text",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="gallery-rail",
                shape="rectangle",
                area=(816, 218, 2, 766),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
            ShapeLayer(
                id="gallery-accent",
                shape="rectangle",
                area=(816, 942, 188, 8),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="gallery-bottom-rule",
                shape="rectangle",
                area=(76, 1204, 928, 2),
                color_token="color.text",
                opacity=0.26,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(76, 76, 476, 34),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.22,
                z_index=10,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=28,
                area=(708, 76, 296, 34),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1292, 1496),
                area=(120, 236, 646, 748),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(842, 240, 162, 126),
                fit="fixed",
                font_size_px=108,
                font_weight=500,
                line_height=0.84,
                text_align="right",
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=30,
                area=(590, 802, 414, 252),
                fit="fixed",
                font_size_px=86,
                font_weight=650,
                line_height=0.92,
                letter_spacing_em=-0.045,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=92,
                area=(590, 1084, 414, 92),
                fit="fixed",
                required=False,
                font_size_px=19,
                line_height=1.24,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 1238, 474, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (872, 1170, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["gallery-root"],
            groups=[
                SceneGroup(
                    id="gallery-root",
                    kind="grid",
                    columns=2,
                    gap_px=50,
                    area=(76, 76, 928, 1226),
                    children=["gallery-header", "gallery-art", "gallery-copy", "gallery-footer"],
                ),
                SceneGroup(
                    id="gallery-header",
                    kind="stack",
                    direction="horizontal",
                    gap_px=156,
                    area=(76, 76, 928, 34),
                    children=["kicker", "issue"],
                ),
                SceneGroup(
                    id="gallery-art",
                    kind="frame",
                    area=(102, 218, 716, 766),
                    children=["gallery-mat", "gallery-shadow", "photo", "gallery-rail"],
                ),
                SceneGroup(
                    id="gallery-copy",
                    kind="stack",
                    direction="vertical",
                    gap_px=30,
                    area=(590, 240, 414, 936),
                    children=["index", "gallery-accent", "headline", "body"],
                ),
                SceneGroup(
                    id="gallery-footer",
                    kind="frame",
                    area=(76, 1170, 928, 132),
                    children=["gallery-bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def _column(ir: BrandIR) -> LayoutSpec:
    layout_id = "luxury-column-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Minimalismo de luxo — Ateliê em coluna",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="column-field",
                shape="rectangle",
                area=(300, 0, 480, 1350),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="column-top-disc",
                shape="circle",
                area=(510, 88, 60, 60),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="column-upper-rule",
                shape="rectangle",
                area=(300, 186, 480, 2),
                color_token="color.text",
                opacity=0.24,
                z_index=2,
            ),
            ShapeLayer(
                id="column-lower-rule",
                shape="rectangle",
                area=(300, 1120, 480, 2),
                color_token="color.text",
                opacity=0.24,
                z_index=2,
            ),
            ShapeLayer(
                id="column-bottom-disc",
                shape="circle",
                area=(524, 1194, 32, 32),
                color_token="color.primary",
                opacity=0.54,
                z_index=3,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(340, 220, 400, 34),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.22,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=36,
                area=(160, 326, 760, 314),
                fit="fixed",
                font_size_px=112,
                font_weight=580,
                line_height=0.9,
                letter_spacing_em=-0.05,
                text_align="center",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=132,
                area=(220, 700, 640, 192),
                fit="fixed",
                required=False,
                font_size_px=24,
                line_height=1.35,
                text_align="center",
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(76, 930, 298, 184),
                fit="fixed",
                font_size_px=164,
                font_weight=500,
                line_height=0.82,
                letter_spacing_em=-0.06,
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(352, 1250, 376, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                text_align="center",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (872, 1138, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["column-root"],
            groups=[
                SceneGroup(
                    id="column-root",
                    kind="grid",
                    columns=1,
                    gap_px=62,
                    area=(0, 0, 1080, 1350),
                    children=["column-structure", "column-message", "column-footer"],
                ),
                SceneGroup(
                    id="column-structure",
                    kind="frame",
                    area=(300, 0, 480, 1226),
                    children=[
                        "column-field",
                        "column-top-disc",
                        "column-upper-rule",
                        "column-lower-rule",
                        "column-bottom-disc",
                    ],
                ),
                SceneGroup(
                    id="column-message",
                    kind="stack",
                    direction="vertical",
                    gap_px=60,
                    area=(160, 220, 760, 894),
                    children=["kicker", "headline", "body", "index"],
                ),
                SceneGroup(
                    id="column-footer",
                    kind="frame",
                    area=(352, 1138, 652, 142),
                    children=["signature", "logo"],
                ),
            ],
        ),
    )


def minimal_luxury_package(ir: BrandIR) -> TemplatePackage:
    """Publica três composições em que o luxo nasce de escala e proporção."""
    style = derive_style_system(ir)
    layouts = (_whisper(ir), _gallery(ir), _column(ir))
    samples = {
        "luxury-whisper-post-4x5": {
            "kicker": "Presença em baixa voz",
            "index": "1",
            "headline": "O essencial permanece.",
            "body": "Escala, silêncio e detalhe constroem uma presença sem excesso.",
            "signature": "@sua-marca",
        },
        "luxury-gallery-post-4x5": {
            "kicker": "Caderno de coleção",
            "issue": "Edição 01 · 2026",
            "index": "2",
            "headline": "Matéria em primeiro plano.",
            "body": "Uma imagem ocupa a página; o texto apenas orienta a leitura.",
            "signature": "@sua-marca",
        },
        "luxury-column-post-4x5": {
            "kicker": "Ateliê essencial",
            "headline": "Precisão também emociona.",
            "body": "Uma composição central, contida e deliberada para mensagens que pedem permanência.",
            "index": "3",
            "signature": "@sua-marca",
        },
    }
    intents = {
        "luxury-whisper-post-4x5": (
            "Sussurro monumental",
            "Contrapor um número quase fantasma a uma frase ampla e poucos sinais de acabamento.",
        ),
        "luxury-gallery-post-4x5": (
            "Galeria silenciosa",
            "Tratar a imagem como obra exposta, com texto lateral e metadados discretos.",
        ),
        "luxury-column-post-4x5": (
            "Ateliê em coluna",
            "Concentrar a mensagem num eixo estreito, simétrico e respirado.",
        ),
    }
    compositions = []
    for layout in layouts:
        name, intent = intents[layout.id]
        compositions.append(
            TemplateComposition(
                id=layout.id,
                name_pt=name,
                intent_pt=intent,
                layout=layout,
                sample_content_pt=samples[layout.id],
                critical_nodes=["headline", "logo"],
                export_support=ExportSupport(pptx="native"),
            )
        )
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Minimalismo de luxo",
        title_pt="Minimalismo de luxo",
        description_pt=(
            "Três composições editáveis guiadas por silêncio, proporção e acabamento preciso."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
