"""Família de produto e campanha: hero, benefício e lançamento modular."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "product-campaign"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _hero(ir: BrandIR) -> LayoutSpec:
    layout_id = "product-hero-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Produto e campanha — Produto em primeiro plano",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="product-hero-mat",
                shape="rectangle",
                area=(62, 186, 664, 908),
                color_token="color.primary",
                opacity=0.1,
                z_index=1,
            ),
            ShapeLayer(
                id="product-hero-rail",
                shape="rectangle",
                area=(758, 0, 322, 1350),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="product-hero-price-rule",
                shape="rectangle",
                area=(792, 292, 212, 4),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="product-hero-cta-field",
                shape="rectangle",
                area=(758, 520, 280, 82),
                color_token="color.primary",
                opacity=0.16,
                z_index=2,
            ),
            ShapeLayer(
                id="product-hero-copy-field",
                shape="rectangle",
                area=(482, 772, 556, 322),
                color_token="color.background",
                z_index=4,
            ),
            ShapeLayer(
                id="product-hero-bottom-rule",
                shape="rectangle",
                area=(62, 1178, 976, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(62, 76, 476, 32),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=28,
                area=(738, 76, 300, 32),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1328, 1816),
                area=(62, 186, 664, 908),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="price",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=18,
                area=(792, 320, 212, 136),
                fit="fixed",
                font_size_px=72,
                font_weight=680,
                line_height=0.9,
                text_align="right",
                letter_spacing_em=-0.04,
                z_index=10,
            ),
            Slot(
                id="cta",
                kind="text",
                role="caption",
                max_chars=30,
                area=(780, 545, 236, 32),
                fit="fixed",
                font_size_px=14,
                font_weight=700,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=38,
                area=(512, 800, 492, 174),
                fit="fixed",
                font_size_px=60,
                font_weight=700,
                line_height=0.94,
                letter_spacing_em=-0.045,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=96,
                area=(604, 984, 400, 84),
                fit="fixed",
                required=False,
                font_size_px=18,
                line_height=1.3,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(62, 1216, 470, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (872, 1168, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["product-hero-root"],
            groups=[
                SceneGroup(
                    id="product-hero-root",
                    kind="group",
                    area=(0, 0, 1080, 1350),
                    children=[
                        "product-hero-header",
                        "product-hero-visual",
                        "product-hero-offer",
                        "product-hero-footer",
                    ],
                ),
                SceneGroup(
                    id="product-hero-header",
                    kind="group",
                    area=(62, 76, 976, 32),
                    children=["kicker", "issue"],
                ),
                SceneGroup(
                    id="product-hero-visual",
                    kind="frame",
                    area=(62, 186, 664, 908),
                    children=["product-hero-mat", "photo"],
                ),
                SceneGroup(
                    id="product-hero-offer",
                    kind="group",
                    area=(482, 292, 556, 802),
                    children=[
                        "product-hero-rail",
                        "product-hero-price-rule",
                        "price",
                        "product-hero-cta-field",
                        "cta",
                        "product-hero-copy-field",
                        "headline",
                        "body",
                    ],
                ),
                SceneGroup(
                    id="product-hero-footer",
                    kind="group",
                    area=(62, 1178, 976, 146),
                    children=["product-hero-bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def _benefit(ir: BrandIR) -> LayoutSpec:
    layout_id = "product-benefit-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Produto e campanha — Benefício em evidência",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="benefit-photo-mat",
                shape="rectangle",
                area=(566, 92, 438, 590),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="benefit-divider",
                shape="rectangle",
                area=(522, 92, 2, 1010),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
            ShapeLayer(
                id="benefit-one-field",
                shape="rectangle",
                area=(78, 644, 398, 120),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="benefit-two-field",
                shape="rectangle",
                area=(78, 784, 398, 120),
                color_token="color.primary",
                opacity=0.14,
                z_index=1,
            ),
            ShapeLayer(
                id="benefit-three-field",
                shape="rectangle",
                area=(78, 924, 398, 120),
                color_token="color.primary",
                opacity=0.2,
                z_index=1,
            ),
            ShapeLayer(
                id="benefit-cta-field",
                shape="rectangle",
                area=(566, 934, 438, 110),
                color_token="color.primary",
                opacity=0.18,
                z_index=1,
            ),
            ShapeLayer(
                id="benefit-bottom-rule",
                shape="rectangle",
                area=(78, 1148, 926, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(78, 92, 410, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=40,
                area=(78, 176, 398, 270),
                fit="fixed",
                font_size_px=70,
                font_weight=700,
                line_height=0.92,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=104,
                area=(78, 466, 398, 126),
                fit="fixed",
                required=False,
                font_size_px=19,
                line_height=1.3,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(876, 1180),
                area=(566, 92, 438, 590),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="benefit-one",
                kind="text",
                role="body",
                max_chars=54,
                area=(100, 674, 354, 64),
                fit="fixed",
                font_size_px=20,
                font_weight=600,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="benefit-two",
                kind="text",
                role="body",
                max_chars=54,
                area=(100, 814, 354, 64),
                fit="fixed",
                font_size_px=20,
                font_weight=600,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="benefit-three",
                kind="text",
                role="body",
                max_chars=54,
                area=(100, 954, 354, 64),
                fit="fixed",
                font_size_px=20,
                font_weight=600,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="price",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=18,
                area=(566, 730, 438, 150),
                fit="fixed",
                font_size_px=92,
                font_weight=680,
                line_height=0.88,
                text_align="right",
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="cta",
                kind="text",
                role="caption",
                max_chars=30,
                area=(594, 972, 382, 34),
                fit="fixed",
                font_size_px=15,
                font_weight=700,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(78, 1190, 438, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (872, 1168, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["benefit-root"],
            groups=[
                SceneGroup(
                    id="benefit-root",
                    kind="grid",
                    columns=2,
                    gap_px=42,
                    area=(78, 92, 926, 1224),
                    children=[
                        "benefit-copy",
                        "benefit-divider",
                        "benefit-product",
                        "benefit-list",
                        "benefit-offer",
                        "benefit-footer",
                    ],
                ),
                SceneGroup(
                    id="benefit-copy",
                    kind="stack",
                    direction="vertical",
                    gap_px=40,
                    area=(78, 92, 398, 500),
                    children=["kicker", "headline", "body"],
                ),
                SceneGroup(
                    id="benefit-product",
                    kind="frame",
                    area=(566, 92, 438, 788),
                    children=["benefit-photo-mat", "photo", "price"],
                ),
                SceneGroup(
                    id="benefit-list",
                    kind="stack",
                    direction="vertical",
                    gap_px=20,
                    area=(78, 644, 398, 400),
                    children=[
                        "benefit-one-field",
                        "benefit-one",
                        "benefit-two-field",
                        "benefit-two",
                        "benefit-three-field",
                        "benefit-three",
                    ],
                ),
                SceneGroup(
                    id="benefit-offer",
                    kind="frame",
                    area=(566, 934, 438, 110),
                    children=["benefit-cta-field", "cta"],
                ),
                SceneGroup(
                    id="benefit-footer",
                    kind="frame",
                    area=(78, 1148, 926, 168),
                    children=["benefit-bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def _launch(ir: BrandIR) -> LayoutSpec:
    layout_id = "product-launch-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Produto e campanha — Lançamento modular",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="launch-orbit",
                shape="circle",
                area=(214, 276, 652, 652),
                color_token="color.primary",
                opacity=0.09,
                z_index=1,
            ),
            ShapeLayer(
                id="launch-photo-mat",
                shape="rectangle",
                area=(318, 326, 444, 560),
                color_token="color.text",
                opacity=0.12,
                z_index=2,
            ),
            ShapeLayer(
                id="launch-left-marker",
                shape="circle",
                area=(88, 594, 32, 32),
                color_token="color.primary",
                z_index=4,
            ),
            ShapeLayer(
                id="launch-right-marker",
                shape="circle",
                area=(960, 594, 32, 32),
                color_token="color.primary",
                z_index=4,
            ),
            ShapeLayer(
                id="launch-offer-rule",
                shape="rectangle",
                area=(76, 972, 928, 4),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="launch-cta-field",
                shape="rectangle",
                area=(446, 1094, 286, 82),
                color_token="color.primary",
                opacity=0.18,
                z_index=2,
            ),
            ShapeLayer(
                id="launch-bottom-rule",
                shape="rectangle",
                area=(76, 1210, 928, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 72, 430, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="issue",
                kind="text",
                role="caption",
                max_chars=28,
                area=(690, 72, 314, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=38,
                area=(140, 132, 800, 142),
                fit="fixed",
                font_size_px=66,
                font_weight=700,
                line_height=0.94,
                letter_spacing_em=-0.045,
                text_align="center",
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(888, 1120),
                area=(318, 326, 444, 560),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="price",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=18,
                area=(76, 1008, 306, 118),
                fit="fixed",
                font_size_px=76,
                font_weight=680,
                line_height=0.88,
                letter_spacing_em=-0.05,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=90,
                area=(734, 1008, 270, 112),
                fit="fixed",
                required=False,
                font_size_px=18,
                line_height=1.3,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="cta",
                kind="text",
                role="caption",
                max_chars=30,
                area=(466, 1119, 246, 32),
                fit="fixed",
                font_size_px=14,
                font_weight=700,
                text_align="center",
                text_transform="uppercase",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(76, 1244, 430, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (872, 1168, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["launch-root"],
            groups=[
                SceneGroup(
                    id="launch-root",
                    kind="stack",
                    direction="vertical",
                    gap_px=40,
                    area=(76, 72, 928, 1250),
                    children=["launch-header", "launch-product", "launch-offer", "launch-footer"],
                ),
                SceneGroup(
                    id="launch-header",
                    kind="group",
                    area=(76, 72, 928, 202),
                    children=["kicker", "issue", "headline"],
                ),
                SceneGroup(
                    id="launch-product",
                    kind="group",
                    area=(88, 276, 904, 652),
                    children=[
                        "launch-orbit",
                        "launch-photo-mat",
                        "photo",
                        "launch-left-marker",
                        "launch-right-marker",
                    ],
                ),
                SceneGroup(
                    id="launch-offer",
                    kind="group",
                    area=(76, 972, 928, 204),
                    children=["launch-offer-rule", "price", "launch-cta-field", "cta", "body"],
                ),
                SceneGroup(
                    id="launch-footer",
                    kind="group",
                    area=(76, 1190, 928, 132),
                    children=["launch-bottom-rule", "signature", "logo"],
                ),
            ],
        ),
    )


def product_campaign_package(ir: BrandIR) -> TemplatePackage:
    """Publica três peças de produto sem reintroduzir um fluxo de campanha."""
    style = derive_style_system(ir)
    layouts = (_hero(ir), _benefit(ir), _launch(ir))
    samples = {
        "product-hero-post-4x5": {
            "kicker": "Seleção da temporada",
            "issue": "Edição 01 · 2026",
            "price": "R$ 189",
            "cta": "Conheça a coleção",
            "headline": "Um objeto com presença.",
            "body": "Detalhe, matéria e função reunidos em uma peça essencial.",
            "signature": "@sua-marca",
        },
        "product-benefit-post-4x5": {
            "kicker": "Por que escolher",
            "headline": "Valor que se percebe no uso.",
            "body": "Uma apresentação direta, sem reduzir o produto a uma lista genérica.",
            "benefit-one": "01 · Feito para durar",
            "benefit-two": "02 · Matéria selecionada",
            "benefit-three": "03 · Uso intuitivo",
            "price": "R$ 189",
            "cta": "Ver detalhes",
            "signature": "@sua-marca",
        },
        "product-launch-post-4x5": {
            "kicker": "Novo lançamento",
            "issue": "Disponível agora",
            "headline": "A forma certa de chegar.",
            "price": "R$ 189",
            "body": "Uma estreia construída em torno do produto.",
            "cta": "Descobrir agora",
            "signature": "@sua-marca",
        },
    }
    intents = {
        "product-hero-post-4x5": (
            "Produto em primeiro plano",
            "Combinar fotografia dominante, oferta lateral e argumento editorial sobreposto.",
        ),
        "product-benefit-post-4x5": (
            "Benefício em evidência",
            "Equilibrar imagem, três benefícios, preço e ação numa composição comparativa.",
        ),
        "product-launch-post-4x5": (
            "Lançamento modular",
            "Centralizar o produto como acontecimento e distribuir preço, texto e ação ao redor dele.",
        ),
    }
    compositions = [
        TemplateComposition(
            id=layout.id,
            name_pt=intents[layout.id][0],
            intent_pt=intents[layout.id][1],
            layout=layout,
            sample_content_pt=samples[layout.id],
            critical_nodes=["headline", "logo"],
            export_support=ExportSupport(pptx="native"),
        )
        for layout in layouts
    ]
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Produto e campanha",
        title_pt="Produto e campanha",
        description_pt=(
            "Três templates individuais para apresentar produto, benefícios, preço e ação sem "
            "reativar um modo de campanha separado."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
