"""Família de diagrama técnico: planta, anotação e fluxo de sistema."""

from __future__ import annotations

from brand_runtime.ir.models import BrandIR
from brand_runtime.kit.models import (
    Background,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    ShapeLayer,
    Slot,
)
from brand_runtime.style.derive import derive_style_system
from brand_runtime.templates.foundations import (
    POST_4X5_CANVAS,
    logo_slot,
    publication_evaluations,
    template_ref,
)
from brand_runtime.templates.models import ExportSupport, TemplateComposition, TemplatePackage

PACKAGE_ID = "technical-diagram"
PACKAGE_VERSION = "1.0.0"


def _ref(composition_id: str):
    return template_ref(PACKAGE_ID, PACKAGE_VERSION, composition_id)


def _blueprint(ir: BrandIR) -> LayoutSpec:
    layout_id = "technical-blueprint-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Diagrama técnico — Planta editorial",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="blueprint-frame-top",
                shape="rectangle",
                area=(72, 72, 936, 2),
                color_token="color.text",
                opacity=0.48,
                z_index=2,
            ),
            ShapeLayer(
                id="blueprint-frame-left",
                shape="rectangle",
                area=(72, 72, 2, 1206),
                color_token="color.text",
                opacity=0.48,
                z_index=2,
            ),
            ShapeLayer(
                id="blueprint-frame-right",
                shape="rectangle",
                area=(1006, 72, 2, 1206),
                color_token="color.text",
                opacity=0.48,
                z_index=2,
            ),
            ShapeLayer(
                id="blueprint-frame-bottom",
                shape="rectangle",
                area=(72, 1276, 936, 2),
                color_token="color.text",
                opacity=0.48,
                z_index=2,
            ),
            ShapeLayer(
                id="blueprint-axis-x",
                shape="rectangle",
                area=(72, 686, 936, 2),
                color_token="color.primary",
                opacity=0.38,
                z_index=2,
            ),
            ShapeLayer(
                id="blueprint-axis-y",
                shape="rectangle",
                area=(616, 72, 2, 1206),
                color_token="color.primary",
                opacity=0.38,
                z_index=2,
            ),
            ShapeLayer(
                id="blueprint-target-disc",
                shape="circle",
                area=(700, 252, 246, 246),
                color_token="color.primary",
                opacity=0.08,
                z_index=1,
            ),
            ShapeLayer(
                id="blueprint-target-core",
                shape="circle",
                area=(796, 348, 54, 54),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="blueprint-measure",
                shape="rectangle",
                area=(656, 736, 6, 338),
                color_token="color.primary",
                z_index=3,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(94, 96, 440, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="coordinates",
                kind="text",
                role="caption",
                max_chars=34,
                area=(664, 96, 322, 30),
                fit="fixed",
                required=False,
                font_size_px=12,
                text_align="right",
                letter_spacing_em=0.12,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(94, 176, 266, 164),
                fit="fixed",
                font_size_px=148,
                font_weight=500,
                line_height=0.82,
                opacity=0.13,
                fill_mode="stroke",
                stroke_color_token="color.primary",
                stroke_width_px=2,
                text_format="zero-padded",
                z_index=3,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=42,
                area=(94, 370, 474, 270),
                fit="fixed",
                font_size_px=72,
                font_weight=680,
                line_height=0.92,
                letter_spacing_em=-0.045,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=126,
                area=(94, 738, 430, 172),
                fit="fixed",
                required=False,
                font_size_px=21,
                line_height=1.32,
                z_index=10,
            ),
            Slot(
                id="note",
                kind="text",
                role="caption",
                max_chars=106,
                area=(694, 738, 292, 188),
                fit="fixed",
                required=False,
                font_size_px=16,
                line_height=1.34,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(94, 1226, 452, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (854, 1126, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["blueprint-root"],
            groups=[
                SceneGroup(
                    id="blueprint-root",
                    kind="frame",
                    area=(72, 72, 936, 1206),
                    children=[
                        "blueprint-frame-top",
                        "blueprint-frame-left",
                        "blueprint-frame-right",
                        "blueprint-frame-bottom",
                        "blueprint-axis-x",
                        "blueprint-axis-y",
                        "blueprint-target-disc",
                        "blueprint-target-core",
                        "blueprint-measure",
                        "blueprint-header",
                        "blueprint-copy",
                        "blueprint-data",
                        "blueprint-footer",
                    ],
                ),
                SceneGroup(
                    id="blueprint-header",
                    kind="stack",
                    direction="horizontal",
                    gap_px=130,
                    area=(94, 96, 892, 30),
                    children=["kicker", "coordinates"],
                ),
                SceneGroup(
                    id="blueprint-copy",
                    kind="stack",
                    direction="vertical",
                    gap_px=30,
                    area=(94, 176, 474, 440),
                    children=["index", "headline"],
                ),
                SceneGroup(
                    id="blueprint-data",
                    kind="grid",
                    columns=2,
                    gap_px=170,
                    area=(94, 738, 892, 188),
                    children=["body", "note"],
                ),
                SceneGroup(
                    id="blueprint-footer",
                    kind="frame",
                    area=(94, 1126, 892, 132),
                    children=["signature", "logo"],
                ),
            ],
        ),
    )


def _annotation(ir: BrandIR) -> LayoutSpec:
    layout_id = "technical-annotation-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Diagrama técnico — Objeto anotado",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="annotation-photo-mat",
                shape="rectangle",
                area=(282, 326, 516, 590),
                color_token="color.primary",
                opacity=0.1,
                z_index=1,
            ),
            ShapeLayer(
                id="annotation-cross-x",
                shape="rectangle",
                area=(232, 618, 616, 2),
                color_token="color.primary",
                opacity=0.45,
                z_index=4,
            ),
            ShapeLayer(
                id="annotation-cross-y",
                shape="rectangle",
                area=(539, 276, 2, 690),
                color_token="color.primary",
                opacity=0.45,
                z_index=4,
            ),
            ShapeLayer(
                id="annotation-callout-one",
                shape="rectangle",
                area=(226, 458, 92, 2),
                color_token="color.primary",
                z_index=5,
            ),
            ShapeLayer(
                id="annotation-callout-two",
                shape="rectangle",
                area=(762, 542, 96, 2),
                color_token="color.primary",
                z_index=5,
            ),
            ShapeLayer(
                id="annotation-callout-three",
                shape="rectangle",
                area=(226, 858, 116, 2),
                color_token="color.primary",
                z_index=5,
            ),
            ShapeLayer(
                id="annotation-point-one",
                shape="circle",
                area=(310, 451, 16, 16),
                color_token="color.primary",
                z_index=6,
            ),
            ShapeLayer(
                id="annotation-point-two",
                shape="circle",
                area=(754, 535, 16, 16),
                color_token="color.primary",
                z_index=6,
            ),
            ShapeLayer(
                id="annotation-point-three",
                shape="circle",
                area=(334, 851, 16, 16),
                color_token="color.primary",
                z_index=6,
            ),
            ShapeLayer(
                id="annotation-bottom-rule",
                shape="rectangle",
                area=(78, 1172, 924, 2),
                color_token="color.text",
                opacity=0.3,
                z_index=2,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=42,
                area=(78, 76, 470, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(838, 76, 164, 110),
                fit="fixed",
                font_size_px=96,
                font_weight=520,
                line_height=0.82,
                text_align="right",
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=44,
                area=(78, 138, 700, 174),
                fit="fixed",
                font_size_px=62,
                font_weight=680,
                line_height=0.94,
                letter_spacing_em=-0.04,
                z_index=10,
            ),
            Slot(
                id="photo",
                kind="image",
                min_resolution=(1032, 1180),
                area=(282, 326, 516, 590),
                fit="fixed",
                required=False,
                z_index=3,
            ),
            Slot(
                id="note-one",
                kind="text",
                role="caption",
                max_chars=62,
                area=(78, 404, 148, 116),
                fit="fixed",
                required=False,
                font_size_px=15,
                line_height=1.3,
                z_index=10,
            ),
            Slot(
                id="note-two",
                kind="text",
                role="caption",
                max_chars=62,
                area=(858, 488, 144, 116),
                fit="fixed",
                required=False,
                font_size_px=15,
                line_height=1.3,
                text_align="right",
                z_index=10,
            ),
            Slot(
                id="note-three",
                kind="text",
                role="caption",
                max_chars=62,
                area=(78, 802, 148, 116),
                fit="fixed",
                required=False,
                font_size_px=15,
                line_height=1.3,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=122,
                area=(282, 962, 516, 140),
                fit="fixed",
                required=False,
                font_size_px=20,
                line_height=1.32,
                text_align="center",
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(78, 1212, 430, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (870, 1168, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["annotation-root"],
            groups=[
                SceneGroup(
                    id="annotation-root",
                    kind="group",
                    area=(78, 76, 924, 1248),
                    children=[
                        "annotation-header",
                        "annotation-object",
                        "annotation-notes",
                        "annotation-bottom-rule",
                        "annotation-footer",
                    ],
                ),
                SceneGroup(
                    id="annotation-header",
                    kind="frame",
                    area=(78, 76, 924, 208),
                    children=["kicker", "index", "headline"],
                ),
                SceneGroup(
                    id="annotation-object",
                    kind="frame",
                    area=(232, 276, 616, 690),
                    children=[
                        "annotation-photo-mat",
                        "photo",
                        "annotation-cross-x",
                        "annotation-cross-y",
                        "annotation-point-one",
                        "annotation-point-two",
                        "annotation-point-three",
                    ],
                ),
                SceneGroup(
                    id="annotation-notes",
                    kind="grid",
                    columns=2,
                    gap_px=632,
                    area=(78, 404, 924, 514),
                    children=[
                        "note-one",
                        "annotation-callout-one",
                        "note-two",
                        "annotation-callout-two",
                        "note-three",
                        "annotation-callout-three",
                        "body",
                    ],
                ),
                SceneGroup(
                    id="annotation-footer",
                    kind="frame",
                    area=(78, 1172, 924, 152),
                    children=["signature", "logo"],
                ),
            ],
        ),
    )


def _flow(ir: BrandIR) -> LayoutSpec:
    layout_id = "technical-flow-post-4x5"
    return LayoutSpec(
        id=layout_id,
        profile="post-4x5",
        name_pt="Diagrama técnico — Fluxo de sistema",
        canvas=POST_4X5_CANVAS,
        background=Background(kind="color", color_token="color.background"),
        template_ref=_ref(layout_id),
        locked_layers=[
            ShapeLayer(
                id="flow-rail",
                shape="rectangle",
                area=(94, 464, 892, 2),
                color_token="color.text",
                opacity=0.28,
                z_index=2,
            ),
            ShapeLayer(
                id="flow-node-one",
                shape="rectangle",
                area=(94, 548, 260, 164),
                color_token="color.primary",
                opacity=0.12,
                z_index=1,
            ),
            ShapeLayer(
                id="flow-node-two",
                shape="rectangle",
                area=(410, 676, 260, 164),
                color_token="color.primary",
                opacity=0.2,
                z_index=1,
            ),
            ShapeLayer(
                id="flow-node-three",
                shape="rectangle",
                area=(726, 804, 260, 164),
                color_token="color.primary",
                opacity=0.28,
                z_index=1,
            ),
            ShapeLayer(
                id="flow-link-one-x",
                shape="rectangle",
                area=(354, 628, 88, 4),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="flow-link-one-y",
                shape="rectangle",
                area=(438, 628, 4, 130),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="flow-link-two-x",
                shape="rectangle",
                area=(670, 756, 88, 4),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="flow-link-two-y",
                shape="rectangle",
                area=(754, 756, 4, 130),
                color_token="color.primary",
                z_index=3,
            ),
            ShapeLayer(
                id="flow-origin",
                shape="circle",
                area=(86, 622, 18, 18),
                color_token="color.primary",
                z_index=4,
            ),
            ShapeLayer(
                id="flow-end",
                shape="circle",
                area=(978, 878, 18, 18),
                color_token="color.primary",
                z_index=4,
            ),
        ],
        slots=[
            Slot(
                id="kicker",
                kind="text",
                role="caption",
                max_chars=44,
                area=(94, 80, 470, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_weight=650,
                text_transform="uppercase",
                letter_spacing_em=0.2,
                z_index=10,
            ),
            Slot(
                id="index",
                kind="text",
                role="heading",
                color_token="color.primary",
                max_chars=3,
                area=(790, 104, 196, 150),
                fit="fixed",
                font_size_px=132,
                font_weight=520,
                line_height=0.82,
                text_align="right",
                text_format="zero-padded",
                z_index=10,
            ),
            Slot(
                id="headline",
                kind="text",
                role="heading",
                max_chars=42,
                area=(94, 166, 618, 224),
                fit="fixed",
                font_size_px=72,
                font_weight=680,
                line_height=0.92,
                letter_spacing_em=-0.045,
                z_index=10,
            ),
            Slot(
                id="stage-one",
                kind="text",
                role="body",
                max_chars=58,
                area=(118, 578, 212, 108),
                fit="fixed",
                font_size_px=22,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="stage-two",
                kind="text",
                role="body",
                max_chars=58,
                area=(434, 706, 212, 108),
                fit="fixed",
                font_size_px=22,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="stage-three",
                kind="text",
                role="body",
                max_chars=58,
                area=(750, 834, 212, 108),
                fit="fixed",
                font_size_px=22,
                line_height=1.2,
                z_index=10,
            ),
            Slot(
                id="body",
                kind="text",
                role="body",
                max_chars=124,
                area=(94, 1018, 602, 140),
                fit="fixed",
                required=False,
                font_size_px=20,
                line_height=1.32,
                z_index=10,
            ),
            Slot(
                id="signature",
                kind="text",
                role="caption",
                max_chars=42,
                area=(94, 1230, 440, 30),
                fit="fixed",
                required=False,
                font_size_px=13,
                font_style="italic",
                letter_spacing_em=0.06,
                z_index=10,
            ),
            logo_slot(ir, (854, 1128, 132, 132)),
        ],
        scene_graph=SceneGraph(
            roots=["flow-root"],
            groups=[
                SceneGroup(
                    id="flow-root",
                    kind="stack",
                    direction="vertical",
                    gap_px=58,
                    area=(86, 80, 910, 1180),
                    children=["flow-header", "flow-rail", "flow-steps", "flow-footer"],
                ),
                SceneGroup(
                    id="flow-header",
                    kind="group",
                    area=(94, 80, 892, 310),
                    children=["kicker", "index", "headline"],
                ),
                SceneGroup(
                    id="flow-steps",
                    kind="group",
                    area=(86, 548, 910, 420),
                    children=[
                        "flow-node-one",
                        "stage-one",
                        "flow-link-one-x",
                        "flow-link-one-y",
                        "flow-node-two",
                        "stage-two",
                        "flow-link-two-x",
                        "flow-link-two-y",
                        "flow-node-three",
                        "stage-three",
                        "flow-origin",
                        "flow-end",
                    ],
                ),
                SceneGroup(
                    id="flow-footer",
                    kind="group",
                    area=(94, 1018, 892, 242),
                    children=["body", "signature", "logo"],
                ),
            ],
        ),
    )


def technical_diagram_package(ir: BrandIR) -> TemplatePackage:
    """Publica três diagramas editoriais feitos de elementos nativos."""
    style = derive_style_system(ir)
    layouts = (_blueprint(ir), _annotation(ir), _flow(ir))
    samples = {
        "technical-blueprint-post-4x5": {
            "kicker": "Caderno de especificação",
            "coordinates": "X 041 · Y 028 · REV 03",
            "index": "1",
            "headline": "Clareza também é estrutura.",
            "body": "Cada decisão ocupa uma posição precisa dentro do sistema.",
            "note": "Nota 04 — relações, margens e hierarquia permanecem visíveis.",
            "signature": "@sua-marca",
        },
        "technical-annotation-post-4x5": {
            "kicker": "Anatomia de uma escolha",
            "index": "2",
            "headline": "Um objeto. Três leituras.",
            "note-one": "01 · matéria",
            "note-two": "02 · função",
            "note-three": "03 · detalhe",
            "body": "As anotações transformam observação em argumento visual.",
            "signature": "@sua-marca",
        },
        "technical-flow-post-4x5": {
            "kicker": "Sistema em movimento",
            "index": "3",
            "headline": "Da intenção até a forma.",
            "stage-one": "01\nLer o contexto",
            "stage-two": "02\nDefinir a direção",
            "stage-three": "03\nConstruir a peça",
            "body": "Um fluxo legível torna o processo parte da comunicação.",
            "signature": "@sua-marca",
        },
    }
    intents = {
        "technical-blueprint-post-4x5": (
            "Planta editorial",
            "Organizar argumento, índice, coordenadas e nota sobre uma malha técnica explícita.",
        ),
        "technical-annotation-post-4x5": (
            "Objeto anotado",
            "Transformar uma imagem central em objeto de estudo por chamadas e pontos de leitura.",
        ),
        "technical-flow-post-4x5": (
            "Fluxo de sistema",
            "Explicar uma sequência em três estágios conectados sem perder autoria editorial.",
        ),
    }
    compositions = [
        TemplateComposition(
            id=layout.id,
            name_pt=intents[layout.id][0],
            intent_pt=intents[layout.id][1],
            layout=layout,
            sample_content_pt=samples[layout.id],
            critical_nodes=["headline", "logo"],
            export_support=ExportSupport(pptx="native"),
        )
        for layout in layouts
    ]
    return TemplatePackage(
        id=PACKAGE_ID,
        version=PACKAGE_VERSION,
        family="Diagrama técnico",
        title_pt="Diagrama técnico",
        description_pt=(
            "Três composições para explicar sistemas, objetos e processos com grades, chamadas "
            "e conectores totalmente editáveis."
        ),
        profiles=["post-4x5"],
        required_roles=list(style.typography),
        required_color_tokens=["color.background", "color.text", "color.primary"],
        compositions=compositions,
        evaluations=publication_evaluations(),
    )
