"""API pública do motor de marca do brand-runtime."""

from brand_runtime.ecosystem import (
    BrandPackageManifest,
    PackageValidationError,
    PackageValidationReport,
    validate_brand_package,
)
from brand_runtime.artifacts import (
    ArtifactInstance,
    ArtifactValue,
    artifact_from_content_spec,
    artifact_to_content_spec,
)
from brand_runtime.guard.static_checks import GuardCheck, GuardVerdict, run_static_checks
from brand_runtime.intake.compile import Answers, CompileError, compile_ir
from brand_runtime.intake.draft import BrandDraft, build_draft
from brand_runtime.ir.models import BrandIR
from brand_runtime.ir.schema import export_schemas
from brand_runtime.kit.carousel import CarouselProfile, generate_carousel_layouts
from brand_runtime.kit.direction import apply_creative_direction, suggested_surface
from brand_runtime.kit.generator import KitGenerationError, generate_kit
from brand_runtime.kit.models import (
    ContentSpec,
    LayoutSpec,
    SceneGraph,
    SceneGroup,
    TemplateRef,
    materialize_content_layout,
)
from brand_runtime.native import (
    canonical_ooxml_manifest,
    derive_branded_template,
    inspect_semantic_shapes,
    render_docx,
    render_native_preview,
    render_pptx,
    validate_ooxml,
)
from brand_runtime.roundtrip import (
    DocumentGraph,
    DocxBrandPlan,
    DocxBrandResult,
    FixPlan,
    FixResult,
    RoundtripReport,
    analyze_docx_brand,
    apply_docx_brand_plan,
    apply_pptx_fix_plan,
    build_fix_plan,
    lint_roundtrip,
    parse_pptx_document_graph,
)
from brand_runtime.style import StyleSystemIR, derive_style_system
from brand_runtime.template_corpus import (
    TemplateCorpusError,
    TemplateCorpusManifest,
    TemplateCorpusReport,
    TemplateGrammar,
    TemplateGrammarAxes,
    TemplateReferenceManifest,
    audit_template_corpus,
)
from brand_runtime.templates import (
    TemplatePackage,
    constructivist_dynamics_package,
    data_evidence_package,
    device_mockup_package,
    editorial_collage_package,
    fashion_editorial_package,
    generate_template_layouts,
    geometric_modernism_package,
    kinetic_typography_package,
    minimal_luxury_package,
    product_campaign_package,
    swiss_system_package,
    template_packages,
    technical_diagram_package,
    typographic_brutalist_package,
    typographic_editorial_package,
)

__version__ = "0.2.1"

__all__ = [
    "Answers",
    "ArtifactInstance",
    "ArtifactValue",
    "BrandDraft",
    "BrandIR",
    "BrandPackageManifest",
    "CarouselProfile",
    "CompileError",
    "ContentSpec",
    "DocumentGraph",
    "DocxBrandPlan",
    "DocxBrandResult",
    "FixPlan",
    "FixResult",
    "GuardCheck",
    "GuardVerdict",
    "KitGenerationError",
    "LayoutSpec",
    "PackageValidationError",
    "PackageValidationReport",
    "RoundtripReport",
    "SceneGraph",
    "SceneGroup",
    "StyleSystemIR",
    "TemplatePackage",
    "TemplateCorpusError",
    "TemplateCorpusManifest",
    "TemplateCorpusReport",
    "TemplateGrammar",
    "TemplateGrammarAxes",
    "TemplateReferenceManifest",
    "TemplateRef",
    "analyze_docx_brand",
    "apply_creative_direction",
    "artifact_from_content_spec",
    "artifact_to_content_spec",
    "audit_template_corpus",
    "apply_docx_brand_plan",
    "apply_pptx_fix_plan",
    "build_draft",
    "build_fix_plan",
    "canonical_ooxml_manifest",
    "compile_ir",
    "constructivist_dynamics_package",
    "data_evidence_package",
    "device_mockup_package",
    "editorial_collage_package",
    "derive_branded_template",
    "derive_style_system",
    "export_schemas",
    "fashion_editorial_package",
    "generate_kit",
    "generate_template_layouts",
    "geometric_modernism_package",
    "kinetic_typography_package",
    "minimal_luxury_package",
    "product_campaign_package",
    "generate_carousel_layouts",
    "inspect_semantic_shapes",
    "lint_roundtrip",
    "materialize_content_layout",
    "parse_pptx_document_graph",
    "render_docx",
    "render_native_preview",
    "render_pptx",
    "run_static_checks",
    "suggested_surface",
    "swiss_system_package",
    "template_packages",
    "technical_diagram_package",
    "typographic_brutalist_package",
    "typographic_editorial_package",
    "validate_ooxml",
    "validate_brand_package",
]
