export const SLOT_LABELS: Record<string, string> = {
  kicker: "Frase de apoio",
  headline: "Frase principal",
  index: "Número",
  signature: "Assinatura",
  title: "Título",
  quote: "Citação",
  author: "Autor(a)",
  body: "Texto",
  caption: "Legenda",
  photo: "Foto",
  "photo-primary": "Foto principal",
  "photo-secondary": "Foto secundária",
  "photo-one": "Foto 1",
  "photo-two": "Foto 2",
  "photo-three": "Foto 3",
  "photo-four": "Foto 4",
  issue: "Edição",
  "signal-word": "Palavra-sinal",
  coordinates: "Coordenadas",
  note: "Nota técnica",
  "note-one": "Nota 1",
  "note-two": "Nota 2",
  "note-three": "Nota 3",
  "stage-one": "Etapa 1",
  "stage-two": "Etapa 2",
  "stage-three": "Etapa 3",
  price: "Preço",
  cta: "Chamada para ação",
  "benefit-one": "Benefício 1",
  "benefit-two": "Benefício 2",
  "benefit-three": "Benefício 3",
  period: "Período",
  metric: "Métrica principal",
  delta: "Variação",
  source: "Fonte dos dados",
  "label-one": "Indicador 1",
  "label-two": "Indicador 2",
  "label-three": "Indicador 3",
  "label-left": "Rótulo esquerdo",
  "label-right": "Rótulo direito",
  "value-left": "Valor esquerdo",
  "value-right": "Valor direito",
  "body-left": "Explicação esquerda",
  "body-right": "Explicação direita",
  verdict: "Conclusão",
  "metric-one": "Métrica 1",
  "metric-two": "Métrica 2",
  "metric-three": "Métrica 3",
  url: "Endereço da interface",
}

export function slotLabel(slotId: string): string {
  return SLOT_LABELS[slotId] ?? `${slotId.charAt(0).toLocaleUpperCase("pt-BR")}${slotId.slice(1)}`
}
